//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/katsura/Documents/objective-c/PIRIKA/PIRIKA/java/com/katsura/iProlog/PrologInterface.java
//
//  Created by katsura on 5/21/14.
//

#ifndef _ComKatsuraIPrologPrologInterface_H_
#define _ComKatsuraIPrologPrologInterface_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlLogicGoal;
@class ComIgormaznitsaProlLogicProlContext;

#import "JreEmulation.h"

@interface ComKatsuraIPrologPrologInterface : NSObject {
 @public
  ComIgormaznitsaProlLogicProlContext *context_;
  NSString *name_;
  ComIgormaznitsaProlLogicGoal *goal_;
}

- (id)init;
- (id)initWithNSString:(NSString *)name;
- (void)clearEngine;
- (NSString *)fileInputWithNSString:(NSString *)fileName;
- (ComIgormaznitsaProlDataTerm *)userInputWithNSString:(NSString *)input;
- (ComIgormaznitsaProlDataTerm *)fail;
- (NSString *)resultTerm2stringWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term;
- (NSString *)listing;
- (void)copyAllFieldsTo:(ComKatsuraIPrologPrologInterface *)other;
@end

J2OBJC_FIELD_SETTER(ComKatsuraIPrologPrologInterface, context_, ComIgormaznitsaProlLogicProlContext *)
J2OBJC_FIELD_SETTER(ComKatsuraIPrologPrologInterface, name_, NSString *)
J2OBJC_FIELD_SETTER(ComKatsuraIPrologPrologInterface, goal_, ComIgormaznitsaProlLogicGoal *)

#endif // _ComKatsuraIPrologPrologInterface_H_
