//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/io/ProlTextInputStream.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "com/igormaznitsa/prol/containers/KnowledgeBase.h"
#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/data/TermInteger.h"
#include "com/igormaznitsa/prol/io/ProlStream.h"
#include "com/igormaznitsa/prol/io/ProlStreamManager.h"
#include "com/igormaznitsa/prol/io/ProlTextInputStream.h"
#include "com/igormaznitsa/prol/logic/ProlContext.h"
#include "com/igormaznitsa/prol/parser/ProlReader.h"
#include "com/igormaznitsa/prol/parser/ProlTokenizer.h"
#include "com/igormaznitsa/prol/parser/ProlTreeBuilder.h"
#include "java/io/IOException.h"
#include "java/io/Reader.h"
#include "java/lang/IllegalArgumentException.h"

@implementation ComIgormaznitsaProlIoProlTextInputStream

- (id)initWithJavaIoReader:(JavaIoReader *)reader
withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context {
  if (self = [super init]) {
    self->resourceId_ = @".local";
    self->context_ = context;
    self->reader_ = [[ComIgormaznitsaProlParserProlReader alloc] initWithJavaIoReader:reader];
    self->tokenizer_ = [[ComIgormaznitsaProlParserProlTokenizer alloc] init];
    thisTerm_ = [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:resourceId_];
  }
  return self;
}

- (id)initWithNSString:(NSString *)resourceId
withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context {
  if (self = [super init]) {
    if (resourceId == nil) {
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"The resource ID must not be null"];
    }
    self->resourceId_ = resourceId;
    self->context_ = context;
    JavaIoReader *inReader = [((id<ComIgormaznitsaProlIoProlStreamManager>) nil_chk([((ComIgormaznitsaProlLogicProlContext *) nil_chk(context)) getStreamManager])) getReaderForResourceWithNSString:resourceId];
    if (inReader == nil) {
      @throw [[JavaIoIOException alloc] initWithNSString:[NSString stringWithFormat:@"Resource '%@' has not been found", resourceId]];
    }
    self->reader_ = [[ComIgormaznitsaProlParserProlReader alloc] initWithJavaIoReader:inReader];
    self->tokenizer_ = [[ComIgormaznitsaProlParserProlTokenizer alloc] init];
    thisTerm_ = [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:resourceId];
  }
  return self;
}

- (NSString *)getResourceId {
  return self->resourceId_;
}

- (ComIgormaznitsaProlLogicProlContext *)getContext {
  return self->context_;
}

- (void)close {
  @synchronized(self) {
    {
      [((ComIgormaznitsaProlParserProlReader *) nil_chk(reader_)) close];
    }
  }
}

- (ComIgormaznitsaProlDataTerm *)readToken {
  @synchronized(self) {
    {
      ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *result = [((ComIgormaznitsaProlParserProlTokenizer *) nil_chk(tokenizer_)) nextTokenWithComIgormaznitsaProlParserProlReader:reader_ withComIgormaznitsaProlContainersKnowledgeBase:[((ComIgormaznitsaProlLogicProlContext *) nil_chk(context_)) getKnowledgeBase]];
      if (result == nil) {
        return [ComIgormaznitsaProlIoProlStream END_OF_FILE];
      }
      return [((ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *) nil_chk(result)) getTerm];
    }
  }
}

- (ComIgormaznitsaProlDataTerm *)readTerm {
  @synchronized(self) {
    {
      if (treeBuilder_ == nil) {
        treeBuilder_ = [[ComIgormaznitsaProlParserProlTreeBuilder alloc] initWithComIgormaznitsaProlLogicProlContext:context_];
      }
      ComIgormaznitsaProlDataTerm *term = [((ComIgormaznitsaProlParserProlTreeBuilder *) nil_chk(treeBuilder_)) readPhraseAndMakeTreeWithComIgormaznitsaProlParserProlTokenizer:tokenizer_ withComIgormaznitsaProlParserProlReader:reader_];
      if (term == nil) {
        return [ComIgormaznitsaProlIoProlStream END_OF_FILE];
      }
      else {
        return term;
      }
    }
  }
}

- (ComIgormaznitsaProlDataTermInteger *)readChar {
  @synchronized(self) {
    {
      int chr = [((ComIgormaznitsaProlParserProlReader *) nil_chk(reader_)) read];
      return [[ComIgormaznitsaProlDataTermInteger alloc] initWithInt:chr];
    }
  }
}

- (ComIgormaznitsaProlDataTerm *)getAsTerm {
  return thisTerm_;
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlIoProlTextInputStream *)other {
  [super copyAllFieldsTo:other];
  other->context_ = context_;
  other->reader_ = reader_;
  other->resourceId_ = resourceId_;
  other->thisTerm_ = thisTerm_;
  other->tokenizer_ = tokenizer_;
  other->treeBuilder_ = treeBuilder_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoReader:withComIgormaznitsaProlLogicProlContext:", "ProlTextInputStream", NULL, 0x4, "Ljava.io.IOException;" },
    { "initWithNSString:withComIgormaznitsaProlLogicProlContext:", "ProlTextInputStream", NULL, 0x1, "Ljava.io.IOException;" },
    { "getResourceId", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getContext", NULL, "Lcom.igormaznitsa.prol.logic.ProlContext;", 0x1, NULL },
    { "close", NULL, "V", 0x21, "Ljava.io.IOException;" },
    { "readToken", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x21, "Ljava.io.IOException;" },
    { "readTerm", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x21, "Ljava.io.IOException;" },
    { "readChar", NULL, "Lcom.igormaznitsa.prol.data.TermInteger;", 0x21, "Ljava.io.IOException;" },
    { "getAsTerm", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "tokenizer_", NULL, 0x12, "Lcom.igormaznitsa.prol.parser.ProlTokenizer;" },
    { "reader_", NULL, 0x12, "Lcom.igormaznitsa.prol.parser.ProlReader;" },
    { "treeBuilder_", NULL, 0x2, "Lcom.igormaznitsa.prol.parser.ProlTreeBuilder;" },
    { "context_", NULL, 0x12, "Lcom.igormaznitsa.prol.logic.ProlContext;" },
    { "resourceId_", NULL, 0x12, "Ljava.lang.String;" },
    { "thisTerm_", NULL, 0x12, "Lcom.igormaznitsa.prol.data.Term;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlIoProlTextInputStream = { "ProlTextInputStream", "com.igormaznitsa.prol.io", NULL, 0x1, 9, methods, 6, fields, 0, NULL};
  return &_ComIgormaznitsaProlIoProlTextInputStream;
}

@end
