//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/io/ProlTextReader.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/data/TermInteger.h"
#include "com/igormaznitsa/prol/io/ProlTextReader.h"
#include "java/io/IOException.h"


@interface ComIgormaznitsaProlIoProlTextReader : NSObject
@end

@implementation ComIgormaznitsaProlIoProlTextReader

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "readToken", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x401, "Ljava.io.IOException;" },
    { "readTerm", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x401, "Ljava.io.IOException;" },
    { "readChar", NULL, "Lcom.igormaznitsa.prol.data.TermInteger;", 0x401, "Ljava.io.IOException;" },
    { "getResourceId", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "close", NULL, "V", 0x401, "Ljava.io.IOException;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlIoProlTextReader = { "ProlTextReader", "com.igormaznitsa.prol.io", NULL, 0x201, 5, methods, 0, NULL, 0, NULL};
  return &_ComIgormaznitsaProlIoProlTextReader;
}

@end
