//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/logic/triggers/AbstractProlTrigger.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlLogicTriggersAbstractProlTrigger_H_
#define _ComIgormaznitsaProlLogicTriggersAbstractProlTrigger_H_

@class ComIgormaznitsaProlLogicProlContext;
@class ComIgormaznitsaProlLogicTriggersProlTriggerTypeEnum;
@class ComIgormaznitsaProlLogicTriggersTriggerEvent;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/logic/triggers/ProlTrigger.h"

@interface ComIgormaznitsaProlLogicTriggersAbstractProlTrigger : NSObject < ComIgormaznitsaProlLogicTriggersProlTrigger > {
 @public
  id<JavaUtilMap> signatureMap_;
}

- (id)init;
- (ComIgormaznitsaProlLogicTriggersAbstractProlTrigger *)addSignatureWithNSString:(NSString *)signature
                          withComIgormaznitsaProlLogicTriggersProlTriggerTypeEnum:(ComIgormaznitsaProlLogicTriggersProlTriggerTypeEnum *)observedEvent;
- (ComIgormaznitsaProlLogicTriggersAbstractProlTrigger *)removeSignatureWithNSString:(NSString *)signature;
- (id<JavaUtilMap>)getSignatures;
- (void)onContextHaltingWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)param0;
- (void)onTriggerEventWithComIgormaznitsaProlLogicTriggersTriggerEvent:(ComIgormaznitsaProlLogicTriggersTriggerEvent *)param0;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlLogicTriggersAbstractProlTrigger *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlLogicTriggersAbstractProlTrigger, signatureMap_, id<JavaUtilMap>)

#endif // _ComIgormaznitsaProlLogicTriggersAbstractProlTrigger_H_
