//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/logic/triggers/ProlTriggerGoal.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/logic/Goal.h"
#include "com/igormaznitsa/prol/logic/PreparedGoal.h"
#include "com/igormaznitsa/prol/logic/ProlContext.h"
#include "com/igormaznitsa/prol/logic/triggers/ProlTriggerGoal.h"
#include "com/igormaznitsa/prol/logic/triggers/TriggerEvent.h"
#include "com/igormaznitsa/prol/trace/TraceListener.h"
#include "java/io/IOException.h"
#include "java/lang/InterruptedException.h"
#include "java/lang/NullPointerException.h"

@implementation ComIgormaznitsaProlLogicTriggersProlTriggerGoal

- (id)initWithNSString:(NSString *)triggerGoal
withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context
withComIgormaznitsaProlTraceTraceListener:(id<ComIgormaznitsaProlTraceTraceListener>)tracer {
  if (self = [super init]) {
    if (context == nil) {
      @throw [[JavaLangNullPointerException alloc] initWithNSString:@"Context is null"];
    }
    self->triggerGoal_ = triggerGoal == nil ? nil : [[ComIgormaznitsaProlLogicPreparedGoal alloc] initWithNSString:triggerGoal withComIgormaznitsaProlLogicProlContext:context withComIgormaznitsaProlTraceTraceListener:tracer];
    self->context_ = context;
  }
  return self;
}

- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)triggerGoal
  withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context
withComIgormaznitsaProlTraceTraceListener:(id<ComIgormaznitsaProlTraceTraceListener>)tracer {
  if (self = [super init]) {
    if (context == nil) {
      @throw [[JavaLangNullPointerException alloc] initWithNSString:@"Context is null"];
    }
    self->triggerGoal_ = triggerGoal == nil ? nil : [[ComIgormaznitsaProlLogicPreparedGoal alloc] initWithComIgormaznitsaProlDataTerm:triggerGoal withComIgormaznitsaProlLogicProlContext:context withComIgormaznitsaProlTraceTraceListener:tracer];
    self->context_ = context;
  }
  return self;
}

- (void)onTriggerEventWithComIgormaznitsaProlLogicTriggersTriggerEvent:(ComIgormaznitsaProlLogicTriggersTriggerEvent *)event {
  if (triggerGoal_ != nil) {
    ComIgormaznitsaProlLogicGoal *tobesolved = [triggerGoal_ getNonparametrizedGoalInstance];
    while (YES) {
      ComIgormaznitsaProlDataTerm *result = [((ComIgormaznitsaProlLogicGoal *) nil_chk(tobesolved)) solve];
      if (result == nil) {
        break;
      }
    }
  }
}

- (void)onContextHaltingWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context {
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlLogicTriggersProlTriggerGoal *)other {
  [super copyAllFieldsTo:other];
  other->context_ = context_;
  other->triggerGoal_ = triggerGoal_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withComIgormaznitsaProlLogicProlContext:withComIgormaznitsaProlTraceTraceListener:", "ProlTriggerGoal", NULL, 0x1, "Ljava.io.IOException;Ljava.lang.InterruptedException;" },
    { "initWithComIgormaznitsaProlDataTerm:withComIgormaznitsaProlLogicProlContext:withComIgormaznitsaProlTraceTraceListener:", "ProlTriggerGoal", NULL, 0x1, NULL },
    { "onTriggerEventWithComIgormaznitsaProlLogicTriggersTriggerEvent:", "onTriggerEvent", "V", 0x1, "Ljava.lang.InterruptedException;" },
    { "onContextHaltingWithComIgormaznitsaProlLogicProlContext:", "onContextHalting", "V", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "triggerGoal_", NULL, 0x14, "Lcom.igormaznitsa.prol.logic.PreparedGoal;" },
    { "context_", NULL, 0x14, "Lcom.igormaznitsa.prol.logic.ProlContext;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlLogicTriggersProlTriggerGoal = { "ProlTriggerGoal", "com.igormaznitsa.prol.logic.triggers", NULL, 0x1, 4, methods, 2, fields, 0, NULL};
  return &_ComIgormaznitsaProlLogicTriggersProlTriggerGoal;
}

@end
