//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/logic/triggers/ProlTrigger.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlLogicTriggersProlTrigger_H_
#define _ComIgormaznitsaProlLogicTriggersProlTrigger_H_

@class ComIgormaznitsaProlLogicProlContext;
@class ComIgormaznitsaProlLogicTriggersTriggerEvent;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@protocol ComIgormaznitsaProlLogicTriggersProlTrigger < NSObject, JavaObject >
- (id<JavaUtilMap>)getSignatures;
- (void)onTriggerEventWithComIgormaznitsaProlLogicTriggersTriggerEvent:(ComIgormaznitsaProlLogicTriggersTriggerEvent *)event;
- (void)onContextHaltingWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context;
@end

#endif // _ComIgormaznitsaProlLogicTriggersProlTrigger_H_
