//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/logic/triggers/ProlTrigger.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "com/igormaznitsa/prol/logic/ProlContext.h"
#include "com/igormaznitsa/prol/logic/triggers/ProlTrigger.h"
#include "com/igormaznitsa/prol/logic/triggers/TriggerEvent.h"
#include "java/lang/InterruptedException.h"
#include "java/util/Map.h"


@interface ComIgormaznitsaProlLogicTriggersProlTrigger : NSObject
@end

@implementation ComIgormaznitsaProlLogicTriggersProlTrigger

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getSignatures", NULL, "Ljava.util.Map;", 0x401, NULL },
    { "onTriggerEventWithComIgormaznitsaProlLogicTriggersTriggerEvent:", "onTriggerEvent", "V", 0x401, "Ljava.lang.InterruptedException;" },
    { "onContextHaltingWithComIgormaznitsaProlLogicProlContext:", "onContextHalting", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlLogicTriggersProlTrigger = { "ProlTrigger", "com.igormaznitsa.prol.logic.triggers", NULL, 0x201, 3, methods, 0, NULL, 0, NULL};
  return &_ComIgormaznitsaProlLogicTriggersProlTrigger;
}

@end
