//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/ClauseIterator.java
//
//  Created by katsura on 14/04/13.
//

#include "com/igormaznitsa/prol/containers/ClauseIterator.h"


@interface ComIgormaznitsaProlContainersClauseIterator : NSObject
@end

@implementation ComIgormaznitsaProlContainersClauseIterator

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "cut", NULL, "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlContainersClauseIterator = { "ClauseIterator", "com.igormaznitsa.prol.containers", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComIgormaznitsaProlContainersClauseIterator;
}

@end
