//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/FactIterator.java
//
//  Created by katsura on 14/04/13.
//

#include "com/igormaznitsa/prol/containers/FactIterator.h"


@interface ComIgormaznitsaProlContainersFactIterator : NSObject
@end

@implementation ComIgormaznitsaProlContainersFactIterator

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _ComIgormaznitsaProlContainersFactIterator = { "FactIterator", "com.igormaznitsa.prol.containers", NULL, 0x201, 0, NULL, 0, NULL, 0, NULL};
  return &_ComIgormaznitsaProlContainersFactIterator;
}

@end
