//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/InsideClauseListItem.java
//
//  Created by katsura on 14/04/13.
//

#include "com/igormaznitsa/prol/containers/InsideClauseListItem.h"
#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/data/TermStruct.h"

@implementation ComIgormaznitsaProlContainersInsideClauseListItem

- (ComIgormaznitsaProlDataTerm *)getKeyTerm {
  return keyTerm_;
}

- (ComIgormaznitsaProlDataTermStruct *)getClause {
  return clause_;
}

- (id)initWithComIgormaznitsaProlContainersInsideClauseListItem:(ComIgormaznitsaProlContainersInsideClauseListItem *)prev
          withComIgormaznitsaProlContainersInsideClauseListItem:(ComIgormaznitsaProlContainersInsideClauseListItem *)next
                          withComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)clause {
  if (self = [super init]) {
    previous_ = prev;
    if (prev != nil) {
      [prev setNextWithComIgormaznitsaProlContainersInsideClauseListItem:self];
    }
    self->next_ = next;
    if (next != nil) {
      [next setPreviousWithComIgormaznitsaProlContainersInsideClauseListItem:self];
    }
    self->clause_ = clause;
    if ([((ComIgormaznitsaProlDataTermStruct *) nil_chk(clause)) isFunctorLikeRuleDefinition]) {
      fact_ = NO;
      keyTerm_ = [clause getElementWithInt:0];
    }
    else {
      fact_ = YES;
      keyTerm_ = clause;
    }
  }
  return self;
}

- (BOOL)isFact {
  return fact_;
}

- (ComIgormaznitsaProlContainersInsideClauseListItem *)getPrevious {
  return previous_;
}

- (void)setPreviousWithComIgormaznitsaProlContainersInsideClauseListItem:(ComIgormaznitsaProlContainersInsideClauseListItem *)value {
  previous_ = value;
}

- (ComIgormaznitsaProlContainersInsideClauseListItem *)getNext {
  return next_;
}

- (void)setNextWithComIgormaznitsaProlContainersInsideClauseListItem:(ComIgormaznitsaProlContainersInsideClauseListItem *)value {
  next_ = value;
}

- (void)remove {
  if (previous_ != nil) {
    [previous_ setNextWithComIgormaznitsaProlContainersInsideClauseListItem:[self getNext]];
  }
  if (next_ != nil) {
    [next_ setPreviousWithComIgormaznitsaProlContainersInsideClauseListItem:[self getPrevious]];
  }
}

- (NSString *)description {
  return [((ComIgormaznitsaProlDataTerm *) nil_chk(keyTerm_)) description];
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlContainersInsideClauseListItem *)other {
  [super copyAllFieldsTo:other];
  other->clause_ = clause_;
  other->fact_ = fact_;
  other->keyTerm_ = keyTerm_;
  other->next_ = next_;
  other->previous_ = previous_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getKeyTerm", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x11, NULL },
    { "getClause", NULL, "Lcom.igormaznitsa.prol.data.TermStruct;", 0x11, NULL },
    { "initWithComIgormaznitsaProlContainersInsideClauseListItem:withComIgormaznitsaProlContainersInsideClauseListItem:withComIgormaznitsaProlDataTermStruct:", "InsideClauseListItem", NULL, 0x4, NULL },
    { "isFact", NULL, "Z", 0x11, NULL },
    { "getPrevious", NULL, "Lcom.igormaznitsa.prol.containers.InsideClauseListItem;", 0x11, NULL },
    { "setPreviousWithComIgormaznitsaProlContainersInsideClauseListItem:", "setPrevious", "V", 0x11, NULL },
    { "getNext", NULL, "Lcom.igormaznitsa.prol.containers.InsideClauseListItem;", 0x11, NULL },
    { "setNextWithComIgormaznitsaProlContainersInsideClauseListItem:", "setNext", "V", 0x11, NULL },
    { "remove", NULL, "V", 0x11, NULL },
    { "description", "toString", "Ljava.lang.String;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "previous_", NULL, 0x2, "Lcom.igormaznitsa.prol.containers.InsideClauseListItem;" },
    { "next_", NULL, 0x2, "Lcom.igormaznitsa.prol.containers.InsideClauseListItem;" },
    { "clause_", NULL, 0x12, "Lcom.igormaznitsa.prol.data.TermStruct;" },
    { "keyTerm_", NULL, 0x12, "Lcom.igormaznitsa.prol.data.Term;" },
    { "fact_", NULL, 0x12, "Z" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlContainersInsideClauseListItem = { "InsideClauseListItem", "com.igormaznitsa.prol.containers", NULL, 0x11, 10, methods, 5, fields, 0, NULL};
  return &_ComIgormaznitsaProlContainersInsideClauseListItem;
}

@end
