//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/KnowledgeBase.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlContainersKnowledgeBase_H_
#define _ComIgormaznitsaProlContainersKnowledgeBase_H_

@class ComIgormaznitsaProlContainersOperatorContainer;
@class ComIgormaznitsaProlDataOperator;
@class ComIgormaznitsaProlDataTermStruct;
@class ComIgormaznitsaProlLogicProlContext;
@class IOSObjectArray;
@class JavaIoPrintWriter;
@protocol ComIgormaznitsaProlContainersClauseIterator;
@protocol ComIgormaznitsaProlContainersFactIterator;
@protocol ComIgormaznitsaProlContainersRuleIterator;
@protocol JavaUtilIterator;

#import "JreEmulation.h"

@protocol ComIgormaznitsaProlContainersKnowledgeBase < NSObject, JavaObject >
- (NSString *)getVocabularyId;
- (void)addOperatorsWithComIgormaznitsaProlDataOperatorArray:(IOSObjectArray *)operators;
- (ComIgormaznitsaProlDataOperator *)getOperatorForTypeAndNameWithNSString:(NSString *)name
                                                                   withInt:(int)type;
- (BOOL)removeOperatorWithNSString:(NSString *)name
                           withInt:(int)type;
- (void)addOperatorWithComIgormaznitsaProlDataOperator:(ComIgormaznitsaProlDataOperator *)operator_;
- (ComIgormaznitsaProlContainersOperatorContainer *)findOperatorForNameWithNSString:(NSString *)name;
- (BOOL)hasOperatorStartsWithWithNSString:(NSString *)str;
- (void)writeWithJavaIoPrintWriter:(JavaIoPrintWriter *)writer;
- (id<ComIgormaznitsaProlContainersFactIterator>)getFactIteratorWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_;
- (id<ComIgormaznitsaProlContainersRuleIterator>)getRuleIteratorWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_;
- (id<ComIgormaznitsaProlContainersClauseIterator>)getClauseIteratorWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_;
- (BOOL)assertZWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)clause;
- (BOOL)assertAWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)clause;
- (BOOL)retractAllWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)clause;
- (BOOL)retractAWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)clause;
- (BOOL)retractZWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)clause;
- (void)abolishWithNSString:(NSString *)signature;
- (id<JavaUtilIterator>)getOperatorIterator;
- (id<ComIgormaznitsaProlContainersKnowledgeBase>)makeCopyWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context;
@end

#endif // _ComIgormaznitsaProlContainersKnowledgeBase_H_
