//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/KnowledgeBaseInsideClauseList.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList_H_
#define _ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList_H_

@class ComIgormaznitsaProlContainersInsideClauseListItem;
@class ComIgormaznitsaProlDataTermStruct;
@class JavaIoPrintWriter;

#import "JreEmulation.h"

@interface ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList : NSObject {
 @public
  ComIgormaznitsaProlContainersInsideClauseListItem *first_;
  ComIgormaznitsaProlContainersInsideClauseListItem *last_;
}

- (id)init;
- (BOOL)assertaWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)struct_;
- (BOOL)assertzWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)struct_;
- (BOOL)retractaWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_;
- (BOOL)retractzWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_;
- (int)retractallWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_;
- (int)size;
- (ComIgormaznitsaProlContainersInsideClauseListItem *)findDirectWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_
                                                 withComIgormaznitsaProlContainersInsideClauseListItem:(ComIgormaznitsaProlContainersInsideClauseListItem *)sinceContainer;
- (ComIgormaznitsaProlContainersInsideClauseListItem *)findBackWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_
                                               withComIgormaznitsaProlContainersInsideClauseListItem:(ComIgormaznitsaProlContainersInsideClauseListItem *)sinceContainer;
- (void)writeWithJavaIoPrintWriter:(JavaIoPrintWriter *)writer;
- (ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList *)makeCopy;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList, first_, ComIgormaznitsaProlContainersInsideClauseListItem *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList, last_, ComIgormaznitsaProlContainersInsideClauseListItem *)

#endif // _ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList_H_
