//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/KnowledgeBase.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSObjectArray.h"
#include "com/igormaznitsa/prol/containers/ClauseIterator.h"
#include "com/igormaznitsa/prol/containers/FactIterator.h"
#include "com/igormaznitsa/prol/containers/KnowledgeBase.h"
#include "com/igormaznitsa/prol/containers/OperatorContainer.h"
#include "com/igormaznitsa/prol/containers/RuleIterator.h"
#include "com/igormaznitsa/prol/data/Operator.h"
#include "com/igormaznitsa/prol/data/TermStruct.h"
#include "com/igormaznitsa/prol/logic/ProlContext.h"
#include "java/io/PrintWriter.h"
#include "java/util/Iterator.h"


@interface ComIgormaznitsaProlContainersKnowledgeBase : NSObject
@end

@implementation ComIgormaznitsaProlContainersKnowledgeBase

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getVocabularyId", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "addOperatorsWithComIgormaznitsaProlDataOperatorArray:", "addOperators", "V", 0x401, NULL },
    { "getOperatorForTypeAndNameWithNSString:withInt:", "getOperatorForTypeAndName", "Lcom.igormaznitsa.prol.data.Operator;", 0x401, NULL },
    { "removeOperatorWithNSString:withInt:", "removeOperator", "Z", 0x401, NULL },
    { "addOperatorWithComIgormaznitsaProlDataOperator:", "addOperator", "V", 0x401, NULL },
    { "findOperatorForNameWithNSString:", "findOperatorForName", "Lcom.igormaznitsa.prol.containers.OperatorContainer;", 0x401, NULL },
    { "hasOperatorStartsWithWithNSString:", "hasOperatorStartsWith", "Z", 0x401, NULL },
    { "writeWithJavaIoPrintWriter:", "write", "V", 0x401, NULL },
    { "getFactIteratorWithComIgormaznitsaProlDataTermStruct:", "getFactIterator", "Lcom.igormaznitsa.prol.containers.FactIterator;", 0x401, NULL },
    { "getRuleIteratorWithComIgormaznitsaProlDataTermStruct:", "getRuleIterator", "Lcom.igormaznitsa.prol.containers.RuleIterator;", 0x401, NULL },
    { "getClauseIteratorWithComIgormaznitsaProlDataTermStruct:", "getClauseIterator", "Lcom.igormaznitsa.prol.containers.ClauseIterator;", 0x401, NULL },
    { "assertZWithComIgormaznitsaProlDataTermStruct:", "assertZ", "Z", 0x401, NULL },
    { "assertAWithComIgormaznitsaProlDataTermStruct:", "assertA", "Z", 0x401, NULL },
    { "retractAllWithComIgormaznitsaProlDataTermStruct:", "retractAll", "Z", 0x401, NULL },
    { "retractAWithComIgormaznitsaProlDataTermStruct:", "retractA", "Z", 0x401, NULL },
    { "retractZWithComIgormaznitsaProlDataTermStruct:", "retractZ", "Z", 0x401, NULL },
    { "abolishWithNSString:", "abolish", "V", 0x401, NULL },
    { "getOperatorIterator", NULL, "Ljava.util.Iterator;", 0x401, NULL },
    { "makeCopyWithComIgormaznitsaProlLogicProlContext:", "makeCopy", "Lcom.igormaznitsa.prol.containers.KnowledgeBase;", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlContainersKnowledgeBase = { "KnowledgeBase", "com.igormaznitsa.prol.containers", NULL, 0x201, 19, methods, 0, NULL, 0, NULL};
  return &_ComIgormaznitsaProlContainersKnowledgeBase;
}

@end
