//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/MemoryRuleIterator.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlContainersMemoryRuleIterator_H_
#define _ComIgormaznitsaProlContainersMemoryRuleIterator_H_

@class ComIgormaznitsaProlContainersInsideClauseListItem;
@class ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList;
@class ComIgormaznitsaProlDataTermStruct;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/containers/MemoryClauseIterator.h"
#include "com/igormaznitsa/prol/containers/RuleIterator.h"

@interface ComIgormaznitsaProlContainersMemoryRuleIterator : ComIgormaznitsaProlContainersMemoryClauseIterator < ComIgormaznitsaProlContainersRuleIterator > {
}

- (id)initWithComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList:(ComIgormaznitsaProlContainersKnowledgeBaseInsideClauseList *)list
                                   withComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)template_;
- (ComIgormaznitsaProlContainersInsideClauseListItem *)findFirstElement;
- (ComIgormaznitsaProlDataTermStruct *)next;
@end

#endif // _ComIgormaznitsaProlContainersMemoryRuleIterator_H_
