//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/containers/OperatorContainer.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlContainersOperatorContainer_H_
#define _ComIgormaznitsaProlContainersOperatorContainer_H_

@class ComIgormaznitsaProlDataOperator;
@class JavaIoPrintWriter;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/data/Term.h"

@interface ComIgormaznitsaProlContainersOperatorContainer : ComIgormaznitsaProlDataTerm {
 @public
  ComIgormaznitsaProlDataOperator *opFZ_;
  ComIgormaznitsaProlDataOperator *opZF_;
  ComIgormaznitsaProlDataOperator *opZFZ_;
  int numberAtContainer_;
  BOOL system_;
}

- (id)initWithComIgormaznitsaProlContainersOperatorContainer:(ComIgormaznitsaProlContainersOperatorContainer *)etalon;
- (id)initWithComIgormaznitsaProlDataOperator:(ComIgormaznitsaProlDataOperator *)operator_;
- (id)initWithComIgormaznitsaProlDataOperator:(ComIgormaznitsaProlDataOperator *)operator_
                                  withBoolean:(BOOL)systemOperator;
- (BOOL)isSystem;
- (BOOL)setOperatorWithComIgormaznitsaProlDataOperator:(ComIgormaznitsaProlDataOperator *)operator_;
- (int)getTermType;
- (int)size;
- (ComIgormaznitsaProlDataOperator *)getOperatorIfSingle;
- (ComIgormaznitsaProlDataOperator *)getCompatibleOperatorWithBoolean:(BOOL)leftPresented
                                                          withBoolean:(BOOL)rightPresented;
- (void)writeWithJavaIoPrintWriter:(JavaIoPrintWriter *)writer;
- (ComIgormaznitsaProlDataOperator *)getForTypePreciselyWithInt:(int)type;
- (ComIgormaznitsaProlDataOperator *)getOperatorForTypeFamilyWithInt:(int)type;
- (BOOL)removeOperatorForTypeWithInt:(int)type;
- (ComIgormaznitsaProlContainersOperatorContainer *)makeCopy;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlContainersOperatorContainer *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlContainersOperatorContainer, opFZ_, ComIgormaznitsaProlDataOperator *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlContainersOperatorContainer, opZF_, ComIgormaznitsaProlDataOperator *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlContainersOperatorContainer, opZFZ_, ComIgormaznitsaProlDataOperator *)

#endif // _ComIgormaznitsaProlContainersOperatorContainer_H_
