//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/utils/IntegerHashSet.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlUtilsIntegerHashSet_H_
#define _ComIgormaznitsaProlUtilsIntegerHashSet_H_

@class IOSObjectArray;

#import "JreEmulation.h"

#define ComIgormaznitsaProlUtilsIntegerHashSet_MASK 31
#define ComIgormaznitsaProlUtilsIntegerHashSet_SIZE 32

@interface ComIgormaznitsaProlUtilsIntegerHashSet : NSObject {
 @public
  IOSObjectArray *insideArray_;
}

+ (int)SIZE;
+ (int)MASK;
- (id)init;
- (BOOL)containsWithInt:(int)value;
- (void)addWithInt:(int)value;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlUtilsIntegerHashSet *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlUtilsIntegerHashSet, insideArray_, IOSObjectArray *)

#endif // _ComIgormaznitsaProlUtilsIntegerHashSet_H_
