//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/libraries/PredicateTemplate.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlLibrariesPredicateTemplate_H_
#define _ComIgormaznitsaProlLibrariesPredicateTemplate_H_

@class ComIgormaznitsaProlDataTerm;

#import "JreEmulation.h"

#define ComIgormaznitsaProlLibrariesPredicateTemplate_MODIFIER_SHALL_BE_INSTANTIATED 0
#define ComIgormaznitsaProlLibrariesPredicateTemplate_MODIFIER_SHALL_BE_INSTANTIATED_OR_VARIABLE 3
#define ComIgormaznitsaProlLibrariesPredicateTemplate_MODIFIER_SHALL_BE_VARIABLE 2
#define ComIgormaznitsaProlLibrariesPredicateTemplate_MODIFIER_SHALL_REMAIN_UNALTERED 1
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_ATOM 0
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_ATOMIC 2
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_ATOM_OR_ATOM_LIST 1
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_BYTE 3
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_CALLABLE_TERM 4
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_CHARACTER 5
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_CHARACTER_CODE 6
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_CHARACTER_CODE_LIST 7
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_CHARACTER_LIST 8
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_CLAUSE 9
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_CLOSE_OPTIONS 10
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_COMPOUND_TERM 11
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_EVALUABLE 12
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_FLAG 13
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_HEAD 14
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_INTEGER 18
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_IN_BYTE 15
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_IN_CHARACTER 16
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_IN_CHARACTER_CODE 17
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_IO_MODE 19
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_LIST 20
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_NONVAR 21
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_NON_EMPTY_LIST 34
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_NUMBER 22
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_OPERATOR_SPECIFIER 23
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_PREDICATE_INDICATOR 24
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_READ_OPTIONS 25
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_SOURCE_SINK 26
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_STREAM 27
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_STREAM_OPTIONS 28
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_STREAM_OR_ALIAS 29
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_STREAM_POSITION 30
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_STREAM_PROPERTY 31
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_TERM 32
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_TRIGGEREVENT 35
#define ComIgormaznitsaProlLibrariesPredicateTemplate_TYPE_WRITE_OPTIONS_LIST 33

@interface ComIgormaznitsaProlLibrariesPredicateTemplate : NSObject {
 @public
  int Type_;
  int Modifier_;
}

+ (int)TYPE_ATOM;
+ (int)TYPE_ATOM_OR_ATOM_LIST;
+ (int)TYPE_ATOMIC;
+ (int)TYPE_BYTE;
+ (int)TYPE_CALLABLE_TERM;
+ (int)TYPE_CHARACTER;
+ (int)TYPE_CHARACTER_CODE;
+ (int)TYPE_CHARACTER_CODE_LIST;
+ (int)TYPE_CHARACTER_LIST;
+ (int)TYPE_CLAUSE;
+ (int)TYPE_CLOSE_OPTIONS;
+ (int)TYPE_COMPOUND_TERM;
+ (int)TYPE_EVALUABLE;
+ (int)TYPE_FLAG;
+ (int)TYPE_HEAD;
+ (int)TYPE_IN_BYTE;
+ (int)TYPE_IN_CHARACTER;
+ (int)TYPE_IN_CHARACTER_CODE;
+ (int)TYPE_INTEGER;
+ (int)TYPE_IO_MODE;
+ (int)TYPE_LIST;
+ (int)TYPE_NONVAR;
+ (int)TYPE_NUMBER;
+ (int)TYPE_OPERATOR_SPECIFIER;
+ (int)TYPE_PREDICATE_INDICATOR;
+ (int)TYPE_READ_OPTIONS;
+ (int)TYPE_SOURCE_SINK;
+ (int)TYPE_STREAM;
+ (int)TYPE_STREAM_OPTIONS;
+ (int)TYPE_STREAM_OR_ALIAS;
+ (int)TYPE_STREAM_POSITION;
+ (int)TYPE_STREAM_PROPERTY;
+ (int)TYPE_TERM;
+ (int)TYPE_WRITE_OPTIONS_LIST;
+ (int)TYPE_NON_EMPTY_LIST;
+ (int)TYPE_TRIGGEREVENT;
+ (int)MODIFIER_SHALL_BE_INSTANTIATED;
+ (int)MODIFIER_SHALL_REMAIN_UNALTERED;
+ (int)MODIFIER_SHALL_BE_VARIABLE;
+ (int)MODIFIER_SHALL_BE_INSTANTIATED_OR_VARIABLE;
- (id)initWithInt:(int)modifier
          withInt:(int)type;
- (id)initWithNSString:(NSString *)string;
- (BOOL)checkWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term;
- (void)checkTermForTemplateWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlLibrariesPredicateTemplate *)other;
@end

#endif // _ComIgormaznitsaProlLibrariesPredicateTemplate_H_
