//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/libraries/PredicateProcessor.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlLibrariesPredicateProcessor_H_
#define _ComIgormaznitsaProlLibrariesPredicateProcessor_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlDataTermStruct;
@class ComIgormaznitsaProlLibrariesProlAbstractLibrary;
@class ComIgormaznitsaProlLogicGoal;
@class IOSClass;
@class IOSObjectArray;
@class JavaLangReflectMethod;

#import "JreEmulation.h"

@interface ComIgormaznitsaProlLibrariesPredicateProcessor : NSObject {
 @public
  NSString *predicateSignature_;
  JavaLangReflectMethod *method_;
  ComIgormaznitsaProlLibrariesProlAbstractLibrary *ownerLibrary_;
  BOOL voidResult_;
  BOOL determined_;
  BOOL evaluable_;
  BOOL changesGoalChain_;
  IOSObjectArray *templates_;
}

+ (IOSClass *)voidResultClass;
+ (IOSClass *)annotationDeterminedClass;
+ (IOSClass *)annotationEvaluableClass;
+ (IOSClass *)changesGoalChainClass;
+ (ComIgormaznitsaProlLibrariesPredicateProcessor *)NULL_PROCESSOR;
- (id)initWithComIgormaznitsaProlLibrariesProlAbstractLibrary:(ComIgormaznitsaProlLibrariesProlAbstractLibrary *)owner
                                                 withNSString:(NSString *)signature
                                    withJavaLangReflectMethod:(JavaLangReflectMethod *)method
      withComIgormaznitsaProlLibrariesPredicateTemplateArray2:(IOSObjectArray *)templates;
- (BOOL)doesChangeGoalChain;
- (BOOL)isDetermined;
- (BOOL)isEvaluable;
- (ComIgormaznitsaProlLibrariesProlAbstractLibrary *)getLibrary;
- (NSString *)getSignature;
- (JavaLangReflectMethod *)getMethod;
- (IOSObjectArray *)getTemplates;
- (IOSObjectArray *)checkTemplatesWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)predicate;
- (ComIgormaznitsaProlDataTerm *)executeEvaluableWithComIgormaznitsaProlLogicGoal:(ComIgormaznitsaProlLogicGoal *)goal
                                            withComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)predicate;
- (BOOL)executeWithComIgormaznitsaProlLogicGoal:(ComIgormaznitsaProlLogicGoal *)goal
          withComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)predicate;
- (NSString *)description;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlLibrariesPredicateProcessor *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlLibrariesPredicateProcessor, predicateSignature_, NSString *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlLibrariesPredicateProcessor, method_, JavaLangReflectMethod *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlLibrariesPredicateProcessor, ownerLibrary_, ComIgormaznitsaProlLibrariesProlAbstractLibrary *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlLibrariesPredicateProcessor, templates_, IOSObjectArray *)

#endif // _ComIgormaznitsaProlLibrariesPredicateProcessor_H_
