//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/katsura/Documents/objective-c/PIRIKA/PIRIKA/java/com/katsura/prolog/ArgumentTree.java
//
//  Created by katsura on 14/05/27.
//

#ifndef _ComKatsuraPrologArgumentTree_H_
#define _ComKatsuraPrologArgumentTree_H_

@class IOSObjectArray;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface ComKatsuraPrologArgumentTree : NSObject {
 @public
  IOSObjectArray *prol_;
  IOSObjectArray *tree_;
}

- (void)init__WithNSString:(NSString *)LMAPath
              withNSString:(NSString *)truthvaluePath
           withJavaUtilMap:(id<JavaUtilMap>)userMap OBJC_METHOD_FAMILY_NONE;
- (id<JavaUtilList>)calculateWithNSString:(NSString *)subject;
- (id)init;
- (void)copyAllFieldsTo:(ComKatsuraPrologArgumentTree *)other;
@end

J2OBJC_FIELD_SETTER(ComKatsuraPrologArgumentTree, prol_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComKatsuraPrologArgumentTree, tree_, IOSObjectArray *)

#endif // _ComKatsuraPrologArgumentTree_H_
