//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/katsura/Documents/objective-c/PIRIKA/PIRIKA/java/com/katsura/prolog/Argument.java
//
//  Created by katsura on 14/06/11.
//

#ifndef _ComKatsuraPrologArgument_H_
#define _ComKatsuraPrologArgument_H_

@class IOSObjectArray;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface ComKatsuraPrologArgument : NSObject {
}

+ (IOSObjectArray *)init__WithNSString:(NSString *)LMAPath
                          withNSString:(NSString *)truthvalue
                       withJavaUtilMap:(id<JavaUtilMap>)userMap OBJC_METHOD_FAMILY_NONE;
+ (id<JavaUtilList>)allAttackWithNSString:(NSString *)LMAPath
                             withNSString:(NSString *)truthvalue
                          withJavaUtilMap:(id<JavaUtilMap>)userMap;
+ (int)getNodeNumWithNSString:(NSString *)LMAPath
                 withNSString:(NSString *)truthvalue
              withJavaUtilMap:(id<JavaUtilMap>)userMap;
+ (id<JavaUtilList>)nodeInfoWithNSString:(NSString *)LMAPath
                            withNSString:(NSString *)truthvalue
                         withJavaUtilMap:(id<JavaUtilMap>)userMap;
+ (id<JavaUtilMap>)nodeInfoMapWithNSString:(NSString *)LMAPath
                              withNSString:(NSString *)truthvalue
                           withJavaUtilMap:(id<JavaUtilMap>)userMap;
+ (id<JavaUtilList>)readEALPWithNSString:(NSString *)filePath;
- (id)init;
@end

#endif // _ComKatsuraPrologArgument_H_
