//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/katsura/Documents/objective-c/PIRIKA/PIRIKA/java/com/katsura/prolog/JavaArgumentTree.java
//
//  Created by katsura on 14/06/11.
//

#ifndef _ComKatsuraPrologJavaArgumentTree_H_
#define _ComKatsuraPrologJavaArgumentTree_H_

@class IOSObjectArray;
@protocol JavaUtilList;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface ComKatsuraPrologJavaArgumentTree : NSObject {
 @public
  IOSObjectArray *prol_;
  IOSObjectArray *tree_;
}

- (void)init__WithNSString:(NSString *)LMAPath
              withNSString:(NSString *)truthvaluePath
           withJavaUtilMap:(id<JavaUtilMap>)userMap OBJC_METHOD_FAMILY_NONE;
- (id<JavaUtilList>)calculateWithNSString:(NSString *)subject;
- (id)init;
- (void)copyAllFieldsTo:(ComKatsuraPrologJavaArgumentTree *)other;
@end

J2OBJC_FIELD_SETTER(ComKatsuraPrologJavaArgumentTree, prol_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComKatsuraPrologJavaArgumentTree, tree_, IOSObjectArray *)

#endif // _ComKatsuraPrologJavaArgumentTree_H_
