//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/katsura/Documents/objective-c/PIRIKA/PIRIKA/java/com/katsura/iProlog/PrologInterface.java
//
//  Created by katsura on 14/06/11.
//

#include "Goal.h"
#include "IOSByteArray.h"
#include "IOSClass.h"
#include "KnowledgeBase.h"
#include "ParserException.h"
#include "ProlConsult.h"
#include "ProlContext.h"
#include "ProlStreamManager.h"
#include "PrologInterface.h"
#include "Term.h"
#include "Utils.h"
#include "Var.h"
#include "java/io/ByteArrayOutputStream.h"
#include "java/io/IOException.h"
#include "java/io/PrintWriter.h"
#include "java/io/Reader.h"
#include "java/lang/InterruptedException.h"
#include "java/lang/StringBuffer.h"
#include "java/util/Collection.h"
#include "java/util/Iterator.h"
#include "java/util/Map.h"

@implementation ComKatsuraIPrologPrologInterface

- (id)init {
  return [self initComKatsuraIPrologPrologInterfaceWithNSString:@"test"];
}

- (id)initComKatsuraIPrologPrologInterfaceWithNSString:(NSString *)name {
  if (self = [super init]) {
    context_ = nil;
    name_ = nil;
    goal_ = nil;
    self->context_ = [[ComIgormaznitsaProlLogicProlContext alloc] initWithNSString:name];
  }
  return self;
}

- (id)initWithNSString:(NSString *)name {
  return [self initComKatsuraIPrologPrologInterfaceWithNSString:name];
}

- (void)clearEngine {
  [((ComIgormaznitsaProlLogicProlContext *) nil_chk(self->context_)) halt];
  self->context_ = [[ComIgormaznitsaProlLogicProlContext alloc] initWithNSString:name_];
}

- (NSString *)fileInputWithNSString:(NSString *)fileName {
  id<ComIgormaznitsaProlIoProlStreamManager> streamManager = [((ComIgormaznitsaProlLogicProlContext *) nil_chk(self->context_)) getStreamManager];
  JavaIoReader *reader = nil;
  @try {
    reader = [((id<ComIgormaznitsaProlIoProlStreamManager>) nil_chk(streamManager)) getReaderForResourceWithNSString:fileName];
    ComIgormaznitsaProlParserProlConsult *consulter = [[ComIgormaznitsaProlParserProlConsult alloc] initWithJavaIoReader:reader withComIgormaznitsaProlLogicProlContext:context_];
    [consulter consult];
  }
  @catch (JavaIoIOException *e) {
    return [NSString stringWithString:@"File not found\n"];
  }
  @finally {
    if (reader != nil) {
      @try {
        [reader close];
      }
      @catch (JavaIoIOException *e) {
        [((JavaIoIOException *) nil_chk(e)) printStackTrace];
      }
    }
  }
  return [NSString stringWithString:@"Complete\n"];
}

- (ComIgormaznitsaProlDataTerm *)userInputWithNSString:(NSString *)input {
  @try {
    self->goal_ = nil;
    self->goal_ = [[ComIgormaznitsaProlLogicGoal alloc] initWithNSString:input withComIgormaznitsaProlLogicProlContext:self->context_];
    return [self->goal_ solve];
  }
  @catch (JavaIoIOException *e) {
    [((JavaIoIOException *) nil_chk(e)) printStackTrace];
  }
  @catch (JavaLangInterruptedException *e) {
    [((JavaLangInterruptedException *) nil_chk(e)) printStackTrace];
  }
  return nil;
}

- (ComIgormaznitsaProlDataTerm *)fail {
  if (self->goal_ == nil) {
    return nil;
  }
  @try {
    return [((ComIgormaznitsaProlLogicGoal *) nil_chk(self->goal_)) solve];
  }
  @catch (JavaLangInterruptedException *e) {
    [((JavaLangInterruptedException *) nil_chk(e)) printStackTrace];
  }
  return nil;
}

- (NSString *)resultTerm2stringWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term {
  JavaLangStringBuffer *sb = [[JavaLangStringBuffer alloc] init];
  id<JavaUtilMap> vars = [ComIgormaznitsaProlUtilsUtils fillTableWithVarsWithComIgormaznitsaProlDataTerm:term];
  id<JavaUtilIterator> iter = [((id<JavaUtilCollection>) nil_chk([((id<JavaUtilMap>) nil_chk(vars)) values])) iterator];
  while ([((id<JavaUtilIterator>) nil_chk(iter)) hasNext]) {
    ComIgormaznitsaProlDataVar *variable = [iter next];
    if ([((ComIgormaznitsaProlDataVar *) nil_chk(variable)) isAnonymous]) {
      continue;
    }
    (void) [sb appendWithNSString:[variable getText]];
    (void) [sb appendWithNSString:@"="];
    if ([variable isUndefined]) {
      (void) [sb appendWithNSString:@"???"];
      (void) [sb appendWithNSString:@"\n"];
    }
    else {
      (void) [sb appendWithNSString:[variable description]];
      (void) [sb appendWithNSString:@"\n"];
    }
  }
  return [sb description];
}

- (NSString *)listing {
  JavaIoByteArrayOutputStream *baos = [[JavaIoByteArrayOutputStream alloc] initWithInt:1024];
  JavaIoPrintWriter *out = [[JavaIoPrintWriter alloc] initWithJavaIoOutputStream:baos];
  [((id<ComIgormaznitsaProlContainersKnowledgeBase>) nil_chk([((ComIgormaznitsaProlLogicProlContext *) nil_chk(self->context_)) getKnowledgeBase])) writeWithJavaIoPrintWriter:out];
  @try {
    [baos close];
  }
  @catch (JavaIoIOException *e) {
    [((JavaIoIOException *) nil_chk(e)) printStackTrace];
  }
  @catch (ComIgormaznitsaProlExceptionsParserException *e) {
    (void) [((ComIgormaznitsaProlExceptionsParserException *) nil_chk(e)) getMessage];
  }
  [out flush];
  [out close];
  return [NSString stringWithBytes:[baos toByteArray]];
}

- (void)copyAllFieldsTo:(ComKatsuraIPrologPrologInterface *)other {
  [super copyAllFieldsTo:other];
  other->context_ = context_;
  other->goal_ = goal_;
  other->name_ = name_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", "PrologInterface", NULL, 0x1, "Ljava.io.IOException;Ljava.lang.InterruptedException;" },
    { "initWithNSString:", "PrologInterface", NULL, 0x1, "Ljava.io.IOException;Ljava.lang.InterruptedException;" },
    { "clearEngine", NULL, "V", 0x1, "Ljava.io.IOException;Ljava.lang.InterruptedException;" },
    { "fileInputWithNSString:", "fileInput", "Ljava.lang.String;", 0x1, NULL },
    { "userInputWithNSString:", "userInput", "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
    { "fail", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
    { "resultTerm2stringWithComIgormaznitsaProlDataTerm:", "resultTerm2string", "Ljava.lang.String;", 0x1, NULL },
    { "listing", NULL, "Ljava.lang.String;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "context_", NULL, 0x2, "Lcom.igormaznitsa.prol.logic.ProlContext;" },
    { "name_", NULL, 0x2, "Ljava.lang.String;" },
    { "goal_", NULL, 0x2, "Lcom.igormaznitsa.prol.logic.Goal;" },
  };
  static J2ObjcClassInfo _ComKatsuraIPrologPrologInterface = { "PrologInterface", "com.katsura.iProlog", NULL, 0x1, 8, methods, 3, fields, 0, NULL};
  return &_ComKatsuraIPrologPrologInterface;
}

@end
