//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/easygui/RecentlyOpenedFileFixedList.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList_H_
#define _ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList_H_

@protocol JavaUtilCollection;
@protocol JavaUtilIterator;
@protocol JavaUtilList;

#import "JreEmulation.h"

@interface ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList : NSObject {
 @public
  int maxLen_;
  id<JavaUtilList> paths_;
}

- (id)initWithInt:(int)maxlen;
- (void)clear;
- (void)putWithNSString:(NSString *)path;
- (void)addWithNSString:(NSString *)path;
- (BOOL)isEmpty;
- (id<JavaUtilIterator>)getIterator;
- (id<JavaUtilCollection>)getCollection;
- (void)removeWithNSString:(NSString *)path;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList, paths_, id<JavaUtilList>)

#endif // _ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList_H_
