//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/easygui/RecentlyOpenedFileFixedList.java
//
//  Created by katsura on 14/04/13.
//

#include "com/igormaznitsa/prol/easygui/RecentlyOpenedFileFixedList.h"
#include "java/util/ArrayList.h"
#include "java/util/Collection.h"
#include "java/util/Collections.h"
#include "java/util/Iterator.h"
#include "java/util/LinkedList.h"
#include "java/util/List.h"

@implementation ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList

- (id)initWithInt:(int)maxlen {
  if (self = [super init]) {
    paths_ = [[JavaUtilLinkedList alloc] init];
    maxLen_ = maxlen;
  }
  return self;
}

- (void)clear {
  @synchronized(self) {
    {
      [((id<JavaUtilList>) nil_chk(paths_)) clear];
    }
  }
}

- (void)putWithNSString:(NSString *)path {
  @synchronized(self) {
    {
      if ([((id<JavaUtilList>) nil_chk(paths_)) containsWithId:path]) {
        [paths_ removeWithId:path];
      }
      [paths_ addWithInt:0 withId:path];
      while ([paths_ size] > maxLen_) {
        (void) [paths_ removeWithInt:[paths_ size] - 1];
      }
    }
  }
}

- (void)addWithNSString:(NSString *)path {
  @synchronized(self) {
    {
      if ([((id<JavaUtilList>) nil_chk(paths_)) containsWithId:path]) {
        [paths_ removeWithId:path];
      }
      if ([paths_ size] < maxLen_) {
        [paths_ addWithId:path];
      }
    }
  }
}

- (BOOL)isEmpty {
  @synchronized(self) {
    {
      return [((id<JavaUtilList>) nil_chk(paths_)) isEmpty];
    }
  }
}

- (id<JavaUtilIterator>)getIterator {
  @synchronized(self) {
    {
      return [((JavaUtilLinkedList *) [[JavaUtilLinkedList alloc] initWithJavaUtilCollection:paths_]) iterator];
    }
  }
}

- (id<JavaUtilCollection>)getCollection {
  @synchronized(self) {
    {
      return [JavaUtilCollections unmodifiableCollectionWithJavaUtilCollection:[[JavaUtilArrayList alloc] initWithJavaUtilCollection:paths_]];
    }
  }
}

- (void)removeWithNSString:(NSString *)path {
  @synchronized(self) {
    {
      [((id<JavaUtilList>) nil_chk(paths_)) removeWithId:path];
    }
  }
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList *)other {
  [super copyAllFieldsTo:other];
  other->maxLen_ = maxLen_;
  other->paths_ = paths_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithInt:", "RecentlyOpenedFileFixedList", NULL, 0x1, NULL },
    { "clear", NULL, "V", 0x21, NULL },
    { "putWithNSString:", "put", "V", 0x21, NULL },
    { "addWithNSString:", "add", "V", 0x21, NULL },
    { "isEmpty", NULL, "Z", 0x21, NULL },
    { "getIterator", NULL, "Ljava.util.Iterator;", 0x21, NULL },
    { "getCollection", NULL, "Ljava.util.Collection;", 0x21, NULL },
    { "removeWithNSString:", "remove", "V", 0x21, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "maxLen_", NULL, 0x12, "I" },
    { "paths_", NULL, 0x12, "Ljava.util.List;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList = { "RecentlyOpenedFileFixedList", "com.igormaznitsa.prol.easygui", NULL, 0x1, 8, methods, 2, fields, 0, NULL};
  return &_ComIgormaznitsaProlEasyguiRecentlyOpenedFileFixedList;
}

@end
