//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/parser/ProlTokenizer.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlParserProlTokenizer_H_
#define _ComIgormaznitsaProlParserProlTokenizer_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlParserProlReader;
@class ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult;
@protocol ComIgormaznitsaProlContainersKnowledgeBase;

#import "JreEmulation.h"

#define ComIgormaznitsaProlParserProlTokenizer_INSIDE_STATE_ATOM 1
#define ComIgormaznitsaProlParserProlTokenizer_INSIDE_STATE_FLOAT 6
#define ComIgormaznitsaProlParserProlTokenizer_INSIDE_STATE_INTEGER 5
#define ComIgormaznitsaProlParserProlTokenizer_INSIDE_STATE_LOOKFOR 0
#define ComIgormaznitsaProlParserProlTokenizer_INSIDE_STATE_OPERATOR 3
#define ComIgormaznitsaProlParserProlTokenizer_INSIDE_STATE_STRING 2
#define ComIgormaznitsaProlParserProlTokenizer_INSIDE_STATE_VARIABLE 4

@interface ComIgormaznitsaProlParserProlTokenizer : NSObject {
 @public
  ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *lastPushedTerm_;
  int prevReadTokenLineNum_;
  int prevReadTokenStrPos_;
  int lastReadTokenLineNum_;
  int lastReadTokenStrPos_;
}

+ (int)INSIDE_STATE_LOOKFOR;
+ (int)INSIDE_STATE_ATOM;
+ (int)INSIDE_STATE_STRING;
+ (int)INSIDE_STATE_OPERATOR;
+ (int)INSIDE_STATE_VARIABLE;
+ (int)INSIDE_STATE_INTEGER;
+ (int)INSIDE_STATE_FLOAT;
- (id)init;
- (void)pushTermBackWithComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult:(ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *)object;
- (ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *)peekTokenWithComIgormaznitsaProlParserProlReader:(ComIgormaznitsaProlParserProlReader *)reader
                                                                  withComIgormaznitsaProlContainersKnowledgeBase:(id<ComIgormaznitsaProlContainersKnowledgeBase>)voc;
- (int)getLastTokenStrPos;
- (int)getLastTokenLineNum;
- (void)fixPositionWithComIgormaznitsaProlParserProlReader:(ComIgormaznitsaProlParserProlReader *)reader;
- (void)skipCommentsWithComIgormaznitsaProlParserProlReader:(ComIgormaznitsaProlParserProlReader *)reader;
- (ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *)nextTokenWithComIgormaznitsaProlParserProlReader:(ComIgormaznitsaProlParserProlReader *)reader
                                                                  withComIgormaznitsaProlContainersKnowledgeBase:(id<ComIgormaznitsaProlContainersKnowledgeBase>)voc;
- (ComIgormaznitsaProlDataTerm *)makeTermFromStringWithNSString:(NSString *)string
                                                        withInt:(int)state;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlParserProlTokenizer *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlParserProlTokenizer, lastPushedTerm_, ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *)

#define ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult_STATE_ATOM 1
#define ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult_STATE_LOOKFOR 0
#define ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult_STATE_OPERATOR 3
#define ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult_STATE_STRING 2
#define ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult_STATE_VARIABLE 4

@interface ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult : NSObject {
 @public
  ComIgormaznitsaProlDataTerm *term_;
  int state_;
}

+ (int)STATE_LOOKFOR;
+ (int)STATE_ATOM;
+ (int)STATE_STRING;
+ (int)STATE_OPERATOR;
+ (int)STATE_VARIABLE;
- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term
                                  withInt:(int)state;
- (int)getTermType;
- (NSString *)getText;
- (int)getState;
- (ComIgormaznitsaProlDataTerm *)getTerm;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlParserProlTokenizer_ProlTokenizerResult, term_, ComIgormaznitsaProlDataTerm *)

#endif // _ComIgormaznitsaProlParserProlTokenizer_H_
