//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/parser/ProlConsult.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlParserProlConsult_H_
#define _ComIgormaznitsaProlParserProlConsult_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlLogicGoal;
@class ComIgormaznitsaProlLogicProlContext;
@class ComIgormaznitsaProlParserProlReader;
@class JavaIoInputStream;
@class JavaIoReader;
@class JavaUtilLoggingLogger;
@protocol ComIgormaznitsaProlContainersKnowledgeBase;
@protocol JavaUtilMap;

#import "JreEmulation.h"

@interface ComIgormaznitsaProlParserProlConsult : NSObject {
 @public
  ComIgormaznitsaProlParserProlReader *reader_;
  ComIgormaznitsaProlLogicProlContext *context_;
  id<ComIgormaznitsaProlContainersKnowledgeBase> base_;
}

+ (JavaUtilLoggingLogger *)LOG;
- (id)initWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context;
- (id)initWithNSString:(NSString *)string
withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context;
- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inArg
withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context;
- (id)initWithJavaIoReader:(JavaIoReader *)reader
withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context;
- (id)initWithComIgormaznitsaProlParserProlReader:(ComIgormaznitsaProlParserProlReader *)reader
          withComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context;
- (void)consult;
- (BOOL)processGoalWithNSString:(NSString *)goal
                withJavaUtilMap:(id<JavaUtilMap>)varTable;
- (BOOL)processGoalWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)goalterm
                                   withJavaUtilMap:(id<JavaUtilMap>)varTable;
- (BOOL)solveGoalWithComIgormaznitsaProlLogicGoal:(ComIgormaznitsaProlLogicGoal *)goal
                                  withJavaUtilMap:(id<JavaUtilMap>)varTable;
- (BOOL)processDirectiveWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)directive;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlParserProlConsult *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlParserProlConsult, reader_, ComIgormaznitsaProlParserProlReader *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlParserProlConsult, context_, ComIgormaznitsaProlLogicProlContext *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlParserProlConsult, base_, id<ComIgormaznitsaProlContainersKnowledgeBase>)

#endif // _ComIgormaznitsaProlParserProlConsult_H_
