//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/parser/ProlReader.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSCharArray.h"
#include "IOSClass.h"
#include "com/igormaznitsa/prol/parser/ProlReader.h"
#include "java/io/IOException.h"
#include "java/io/InputStream.h"
#include "java/io/InputStreamReader.h"
#include "java/io/Reader.h"
#include "java/io/StringReader.h"
#include "java/lang/StringBuilder.h"

@implementation ComIgormaznitsaProlParserProlReader

+ (int)INSIDE_CHAR_BUFFER_SIZE {
  return ComIgormaznitsaProlParserProlReader_INSIDE_CHAR_BUFFER_SIZE;
}

- (id)initWithNSString:(NSString *)string {
  return [self initComIgormaznitsaProlParserProlReaderWithJavaIoReader:[[JavaIoStringReader alloc] initWithNSString:string]];
}

- (id)initWithJavaIoInputStream:(JavaIoInputStream *)inStream {
  return [self initComIgormaznitsaProlParserProlReaderWithJavaIoReader:[[JavaIoInputStreamReader alloc] initWithJavaIoInputStream:inStream]];
}

- (id)initComIgormaznitsaProlParserProlReaderWithJavaIoReader:(JavaIoReader *)reader {
  if (self = [super init]) {
    insideCharBuffer_ = [IOSCharArray arrayWithLength:ComIgormaznitsaProlParserProlReader_INSIDE_CHAR_BUFFER_SIZE];
    insideCharBufferPointer_ = 0;
    inReader_ = reader;
    strPos_ = 0;
    lineNum_ = 1;
    strPosPrev_ = strPos_;
    lineNumPrev_ = lineNum_;
  }
  return self;
}

- (id)initWithJavaIoReader:(JavaIoReader *)reader {
  return [self initComIgormaznitsaProlParserProlReaderWithJavaIoReader:reader];
}

- (int)read {
  @synchronized(self) {
    {
      int ch;
      if (insideCharBufferPointer_ > 0) {
        ch = IOSCharArray_Get(nil_chk(insideCharBuffer_), --insideCharBufferPointer_);
      }
      else {
        ch = [((JavaIoReader *) nil_chk(inReader_)) read];
      }
      strPosPrev_ = strPos_;
      lineNumPrev_ = lineNum_;
      if (ch == 0x000a) {
        strPos_ = 0;
        lineNum_++;
      }
      else {
        if (ch >= 0) {
          strPos_++;
        }
      }
      return ch;
    }
  }
}

- (void)pushBufferDifferenceWithNSString:(NSString *)etalon
               withJavaLangStringBuilder:(JavaLangStringBuilder *)buffer {
  @synchronized(self) {
    {
      int chars = [((JavaLangStringBuilder *) nil_chk(buffer)) sequenceLength] - [((NSString *) nil_chk(etalon)) length];
      int pos = [buffer sequenceLength] - 1;
      while (chars > 0) {
        unichar ch = [buffer charAtWithInt:pos--];
        (*IOSCharArray_GetRef(nil_chk(insideCharBuffer_), insideCharBufferPointer_++)) = ch;
        chars--;
        strPos_--;
        if (strPos_ < 1) {
          strPos_ = 1;
        }
        strPosPrev_ = strPos_;
        if (ch == 0x000a) {
          lineNum_--;
          if (lineNum_ < 1) {
            lineNum_ = 1;
          }
          lineNumPrev_ = lineNum_;
        }
      }
    }
  }
}

- (int)getPrevLineNumber {
  return lineNumPrev_;
}

- (int)getPrevStrPos {
  return strPosPrev_;
}

- (int)getLineNumber {
  return lineNum_;
}

- (int)getStrPos {
  return strPos_;
}

- (void)pushCharBackWithChar:(unichar)ch {
  @synchronized(self) {
    {
      (*IOSCharArray_GetRef(nil_chk(insideCharBuffer_), insideCharBufferPointer_++)) = ch;
      if (ch == 0x000a) {
        strPos_ = 1;
        lineNum_--;
        if (lineNum_ <= 0) {
          lineNum_ = 1;
        }
      }
      else {
        strPos_--;
        if (strPos_ <= 0) {
          strPos_ = 1;
        }
      }
    }
  }
}

- (void)close {
  @synchronized(self) {
    {
      [((JavaIoReader *) nil_chk(inReader_)) close];
    }
  }
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlParserProlReader *)other {
  [super copyAllFieldsTo:other];
  other->inReader_ = inReader_;
  other->insideCharBuffer_ = insideCharBuffer_;
  other->insideCharBufferPointer_ = insideCharBufferPointer_;
  other->lineNum_ = lineNum_;
  other->lineNumPrev_ = lineNumPrev_;
  other->strPos_ = strPos_;
  other->strPosPrev_ = strPosPrev_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:", "ProlReader", NULL, 0x1, NULL },
    { "initWithJavaIoInputStream:", "ProlReader", NULL, 0x1, NULL },
    { "initWithJavaIoReader:", "ProlReader", NULL, 0x1, NULL },
    { "read", NULL, "I", 0x21, "Ljava.io.IOException;" },
    { "pushBufferDifferenceWithNSString:withJavaLangStringBuilder:", "pushBufferDifference", "V", 0x21, NULL },
    { "getPrevLineNumber", NULL, "I", 0x1, NULL },
    { "getPrevStrPos", NULL, "I", 0x1, NULL },
    { "getLineNumber", NULL, "I", 0x1, NULL },
    { "getStrPos", NULL, "I", 0x1, NULL },
    { "pushCharBackWithChar:", "pushCharBack", "V", 0x21, NULL },
    { "close", NULL, "V", 0x21, "Ljava.io.IOException;" },
  };
  static J2ObjcFieldInfo fields[] = {
    { "INSIDE_CHAR_BUFFER_SIZE_", NULL, 0x1a, "I" },
    { "inReader_", NULL, 0x12, "Ljava.io.Reader;" },
    { "insideCharBuffer_", NULL, 0x12, "[C" },
    { "insideCharBufferPointer_", NULL, 0x2, "I" },
    { "strPosPrev_", NULL, 0x2, "I" },
    { "lineNumPrev_", NULL, 0x2, "I" },
    { "strPos_", NULL, 0x2, "I" },
    { "lineNum_", NULL, 0x2, "I" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlParserProlReader = { "ProlReader", "com.igormaznitsa.prol.parser", NULL, 0x1, 11, methods, 8, fields, 0, NULL};
  return &_ComIgormaznitsaProlParserProlReader;
}

@end
