//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/logic/DefaultKnowledgeBaseFactory.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlLogicDefaultKnowledgeBaseFactory_H_
#define _ComIgormaznitsaProlLogicDefaultKnowledgeBaseFactory_H_

@class ComIgormaznitsaProlLogicProlContext;
@protocol ComIgormaznitsaProlContainersKnowledgeBase;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/logic/KnowledgeBaseFactory.h"

@interface ComIgormaznitsaProlLogicDefaultKnowledgeBaseFactory : NSObject < ComIgormaznitsaProlLogicKnowledgeBaseFactory > {
}

+ (ComIgormaznitsaProlLogicDefaultKnowledgeBaseFactory *)instance;
+ (void)setInstance:(ComIgormaznitsaProlLogicDefaultKnowledgeBaseFactory *)instance;
+ (ComIgormaznitsaProlLogicDefaultKnowledgeBaseFactory *)getInstance;
- (id<ComIgormaznitsaProlContainersKnowledgeBase>)makeDefaultKnowledgeBaseWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context
                                                                                                     withNSString:(NSString *)knowledgeBasId;
- (id<ComIgormaznitsaProlContainersKnowledgeBase>)makeKnowledgeBaseWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context
                                                                                              withNSString:(NSString *)knowledgeBaseId
                                                                                              withNSString:(NSString *)type;
- (id)init;
@end

#endif // _ComIgormaznitsaProlLogicDefaultKnowledgeBaseFactory_H_
