//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/logic/KnowledgeBaseFactory.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlLogicKnowledgeBaseFactory_H_
#define _ComIgormaznitsaProlLogicKnowledgeBaseFactory_H_

@class ComIgormaznitsaProlLogicProlContext;
@protocol ComIgormaznitsaProlContainersKnowledgeBase;

#import "JreEmulation.h"

@protocol ComIgormaznitsaProlLogicKnowledgeBaseFactory < NSObject, JavaObject >
- (id<ComIgormaznitsaProlContainersKnowledgeBase>)makeDefaultKnowledgeBaseWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context
                                                                                                     withNSString:(NSString *)knowledgeBasId;
- (id<ComIgormaznitsaProlContainersKnowledgeBase>)makeKnowledgeBaseWithComIgormaznitsaProlLogicProlContext:(ComIgormaznitsaProlLogicProlContext *)context
                                                                                              withNSString:(NSString *)knowledgeBaseId
                                                                                              withNSString:(NSString *)type;
@end

#endif // _ComIgormaznitsaProlLogicKnowledgeBaseFactory_H_
