//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlCriticalError.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlCriticalError_H_
#define _ComIgormaznitsaProlExceptionsProlCriticalError_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/Error.h"

#define ComIgormaznitsaProlExceptionsProlCriticalError_serialVersionUID 1340153646373377400LL

@interface ComIgormaznitsaProlExceptionsProlCriticalError : JavaLangError {
}

+ (long long int)serialVersionUID;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)message
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)message;
- (id)init;
@end

#endif // _ComIgormaznitsaProlExceptionsProlCriticalError_H_
