//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlForkExecutionException.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlForkExecutionException_H_
#define _ComIgormaznitsaProlExceptionsProlForkExecutionException_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlDataTermStruct;
@class IOSObjectArray;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"

#define ComIgormaznitsaProlExceptionsProlForkExecutionException_serialVersionUID 3401072948341099491LL

@interface ComIgormaznitsaProlExceptionsProlForkExecutionException : ComIgormaznitsaProlExceptionsProlAbstractCatcheableException {
 @public
  IOSObjectArray *throwables_;
}

+ (long long int)serialVersionUID;
+ (ComIgormaznitsaProlDataTerm *)ERROR_TERM;
- (IOSObjectArray *)getThrowables;
- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
               withJavaLangThrowableArray:(IOSObjectArray *)causes;
- (id)initWithNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
withJavaLangThrowableArray:(IOSObjectArray *)causes;
- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct;
- (ComIgormaznitsaProlDataTermStruct *)getAsStruct;
- (NSString *)description;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlForkExecutionException *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlExceptionsProlForkExecutionException, throwables_, IOSObjectArray *)

#endif // _ComIgormaznitsaProlExceptionsProlForkExecutionException_H_
