//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlInstantiationErrorException.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlInstantiationErrorException_H_
#define _ComIgormaznitsaProlExceptionsProlInstantiationErrorException_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlDataTermStruct;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"

#define ComIgormaznitsaProlExceptionsProlInstantiationErrorException_serialVersionUID -5157739502740121566LL

@interface ComIgormaznitsaProlExceptionsProlInstantiationErrorException : ComIgormaznitsaProlExceptionsProlAbstractCatcheableException {
}

+ (long long int)serialVersionUID;
+ (ComIgormaznitsaProlDataTerm *)TERM_ERROR;
- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
                    withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct;
- (ComIgormaznitsaProlDataTermStruct *)getAsStruct;
@end

#endif // _ComIgormaznitsaProlExceptionsProlInstantiationErrorException_H_
