//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlTypeErrorException.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlTypeErrorException_H_
#define _ComIgormaznitsaProlExceptionsProlTypeErrorException_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlDataTermStruct;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"

#define ComIgormaznitsaProlExceptionsProlTypeErrorException_serialVersionUID -3258214534404942716LL

@interface ComIgormaznitsaProlExceptionsProlTypeErrorException : ComIgormaznitsaProlExceptionsProlAbstractCatcheableException {
 @public
  NSString *validType_;
}

+ (long long int)serialVersionUID;
+ (ComIgormaznitsaProlDataTerm *)TERM_ERROR;
- (id)initWithNSString:(NSString *)validType
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)validType
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)validType
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (id)initWithNSString:(NSString *)validType
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (NSString *)getValidType;
- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct;
- (ComIgormaznitsaProlDataTermStruct *)getAsStruct;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlTypeErrorException *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlExceptionsProlTypeErrorException, validType_, NSString *)

#endif // _ComIgormaznitsaProlExceptionsProlTypeErrorException_H_
