//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlRepresentationErrorException.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/data/TermStruct.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"
#include "com/igormaznitsa/prol/exceptions/ProlRepresentationErrorException.h"
#include "java/lang/Throwable.h"

@implementation ComIgormaznitsaProlExceptionsProlRepresentationErrorException

static ComIgormaznitsaProlDataTerm * ComIgormaznitsaProlExceptionsProlRepresentationErrorException_TERM_ERROR_;

+ (long long int)serialVersionUID {
  return ComIgormaznitsaProlExceptionsProlRepresentationErrorException_serialVersionUID;
}

+ (ComIgormaznitsaProlDataTerm *)TERM_ERROR {
  return ComIgormaznitsaProlExceptionsProlRepresentationErrorException_TERM_ERROR_;
}

- (id)initWithNSString:(NSString *)flag
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  if (self = [super initWithComIgormaznitsaProlDataTerm:culprit withJavaLangThrowable:cause]) {
    self->flag_ = flag;
  }
  return self;
}

- (id)initWithNSString:(NSString *)flag
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  if (self = [super initWithNSString:message withComIgormaznitsaProlDataTerm:culprit withJavaLangThrowable:cause]) {
    self->flag_ = flag;
  }
  return self;
}

- (id)initWithNSString:(NSString *)flag
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit {
  if (self = [super initWithNSString:message withComIgormaznitsaProlDataTerm:culprit]) {
    self->flag_ = flag;
  }
  return self;
}

- (id)initWithNSString:(NSString *)flag
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit {
  if (self = [super initWithComIgormaznitsaProlDataTerm:culprit]) {
    self->flag_ = flag;
  }
  return self;
}

- (NSString *)getFlag {
  return flag_;
}

- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct {
  return ComIgormaznitsaProlExceptionsProlRepresentationErrorException_TERM_ERROR_;
}

- (ComIgormaznitsaProlDataTermStruct *)getAsStruct {
  ComIgormaznitsaProlDataTermStruct *result = [[ComIgormaznitsaProlDataTermStruct alloc] initWithComIgormaznitsaProlDataTerm:ComIgormaznitsaProlExceptionsProlRepresentationErrorException_TERM_ERROR_ withComIgormaznitsaProlDataTermArray:[IOSObjectArray arrayWithObjects:(id[]){ self->flag_ == nil ? [ComIgormaznitsaProlExceptionsProlAbstractCatcheableException UNDEFINED] : [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:self->flag_] } count:1 type:[IOSClass classWithClass:[ComIgormaznitsaProlDataTerm class]]]];
  [result setCarriedObjectWithJavaIoSerializable:self];
  return result;
}

+ (void)initialize {
  if (self == [ComIgormaznitsaProlExceptionsProlRepresentationErrorException class]) {
    ComIgormaznitsaProlExceptionsProlRepresentationErrorException_TERM_ERROR_ = [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:@"representation_error"];
  }
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlRepresentationErrorException *)other {
  [super copyAllFieldsTo:other];
  other->flag_ = flag_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withComIgormaznitsaProlDataTerm:withJavaLangThrowable:", "ProlRepresentationErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withNSString:withComIgormaznitsaProlDataTerm:withJavaLangThrowable:", "ProlRepresentationErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withNSString:withComIgormaznitsaProlDataTerm:", "ProlRepresentationErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withComIgormaznitsaProlDataTerm:", "ProlRepresentationErrorException", NULL, 0x1, NULL },
    { "getFlag", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getFunctorForErrorStruct", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
    { "getAsStruct", NULL, "Lcom.igormaznitsa.prol.data.TermStruct;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J" },
    { "TERM_ERROR_", NULL, 0x1a, "Lcom.igormaznitsa.prol.data.Term;" },
    { "flag_", NULL, 0x12, "Ljava.lang.String;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlExceptionsProlRepresentationErrorException = { "ProlRepresentationErrorException", "com.igormaznitsa.prol.exceptions", NULL, 0x1, 7, methods, 3, fields, 0, NULL};
  return &_ComIgormaznitsaProlExceptionsProlRepresentationErrorException;
}

@end
