//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlDomainErrorException.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlDomainErrorException_H_
#define _ComIgormaznitsaProlExceptionsProlDomainErrorException_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlDataTermStruct;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"

#define ComIgormaznitsaProlExceptionsProlDomainErrorException_serialVersionUID -7481773982226534683LL

@interface ComIgormaznitsaProlExceptionsProlDomainErrorException : ComIgormaznitsaProlExceptionsProlAbstractCatcheableException {
 @public
  NSString *validDomain_;
}

+ (long long int)serialVersionUID;
+ (ComIgormaznitsaProlDataTerm *)ERROR_TERM;
- (id)initWithNSString:(NSString *)validDomain
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)validDomain
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)validDomain
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (id)initWithNSString:(NSString *)validDomain
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (NSString *)getValidDomain;
- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct;
- (ComIgormaznitsaProlDataTermStruct *)getAsStruct;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlDomainErrorException *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlExceptionsProlDomainErrorException, validDomain_, NSString *)

#endif // _ComIgormaznitsaProlExceptionsProlDomainErrorException_H_
