//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlEvaluationErrorException.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/data/TermStruct.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"
#include "com/igormaznitsa/prol/exceptions/ProlEvaluationErrorException.h"
#include "java/lang/Throwable.h"

@implementation ComIgormaznitsaProlExceptionsProlEvaluationErrorException

static ComIgormaznitsaProlDataTerm * ComIgormaznitsaProlExceptionsProlEvaluationErrorException_TERM_ERROR_;

+ (long long int)serialVersionUID {
  return ComIgormaznitsaProlExceptionsProlEvaluationErrorException_serialVersionUID;
}

+ (ComIgormaznitsaProlDataTerm *)TERM_ERROR {
  return ComIgormaznitsaProlExceptionsProlEvaluationErrorException_TERM_ERROR_;
}

- (id)initWithNSString:(NSString *)error
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  if (self = [super initWithComIgormaznitsaProlDataTerm:culprit withJavaLangThrowable:cause]) {
    self->error_ = error;
  }
  return self;
}

- (id)initWithNSString:(NSString *)error
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  if (self = [super initWithNSString:message withComIgormaznitsaProlDataTerm:culprit withJavaLangThrowable:cause]) {
    self->error_ = error;
  }
  return self;
}

- (id)initWithNSString:(NSString *)error
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit {
  if (self = [super initWithNSString:message withComIgormaznitsaProlDataTerm:culprit]) {
    self->error_ = error;
  }
  return self;
}

- (id)initWithNSString:(NSString *)error
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit {
  if (self = [super initWithComIgormaznitsaProlDataTerm:culprit]) {
    self->error_ = error;
  }
  return self;
}

- (NSString *)getError {
  return self->error_;
}

- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct {
  return ComIgormaznitsaProlExceptionsProlEvaluationErrorException_TERM_ERROR_;
}

- (ComIgormaznitsaProlDataTermStruct *)getAsStruct {
  ComIgormaznitsaProlDataTermStruct *result = [[ComIgormaznitsaProlDataTermStruct alloc] initWithComIgormaznitsaProlDataTerm:ComIgormaznitsaProlExceptionsProlEvaluationErrorException_TERM_ERROR_ withComIgormaznitsaProlDataTermArray:[IOSObjectArray arrayWithObjects:(id[]){ self->error_ == nil ? [ComIgormaznitsaProlExceptionsProlAbstractCatcheableException UNDEFINED] : [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:self->error_] } count:1 type:[IOSClass classWithClass:[ComIgormaznitsaProlDataTerm class]]]];
  [result setCarriedObjectWithJavaIoSerializable:self];
  return result;
}

+ (void)initialize {
  if (self == [ComIgormaznitsaProlExceptionsProlEvaluationErrorException class]) {
    ComIgormaznitsaProlExceptionsProlEvaluationErrorException_TERM_ERROR_ = [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:@"evaluation_error"];
  }
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlEvaluationErrorException *)other {
  [super copyAllFieldsTo:other];
  other->error_ = error_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withComIgormaznitsaProlDataTerm:withJavaLangThrowable:", "ProlEvaluationErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withNSString:withComIgormaznitsaProlDataTerm:withJavaLangThrowable:", "ProlEvaluationErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withNSString:withComIgormaznitsaProlDataTerm:", "ProlEvaluationErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withComIgormaznitsaProlDataTerm:", "ProlEvaluationErrorException", NULL, 0x1, NULL },
    { "getError", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getFunctorForErrorStruct", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
    { "getAsStruct", NULL, "Lcom.igormaznitsa.prol.data.TermStruct;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J" },
    { "TERM_ERROR_", NULL, 0x1a, "Lcom.igormaznitsa.prol.data.Term;" },
    { "error_", NULL, 0x12, "Ljava.lang.String;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlExceptionsProlEvaluationErrorException = { "ProlEvaluationErrorException", "com.igormaznitsa.prol.exceptions", NULL, 0x1, 7, methods, 3, fields, 0, NULL};
  return &_ComIgormaznitsaProlExceptionsProlEvaluationErrorException;
}

@end
