//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlCustomErrorException.java
//
//  Created by katsura on 14/04/13.
//

#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/data/TermStruct.h"
#include "com/igormaznitsa/prol/exceptions/ProlCustomErrorException.h"
#include "java/lang/IllegalArgumentException.h"

@implementation ComIgormaznitsaProlExceptionsProlCustomErrorException

+ (long long int)serialVersionUID {
  return ComIgormaznitsaProlExceptionsProlCustomErrorException_serialVersionUID;
}

- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)error
          withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit {
  if (self = [super initWithComIgormaznitsaProlDataTerm:culprit]) {
    if (error == nil) {
      @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:@"Error must not be null"];
    }
    self->error_ = error;
  }
  return self;
}

- (ComIgormaznitsaProlDataTerm *)getError {
  return self->error_;
}

- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct {
  return [((ComIgormaznitsaProlDataTermStruct *) nil_chk([self getAsStruct])) getFunctor];
}

- (ComIgormaznitsaProlDataTermStruct *)getAsStruct {
  ComIgormaznitsaProlDataTermStruct *result = nil;
  if ([((ComIgormaznitsaProlDataTerm *) nil_chk(error_)) getTermType] == ComIgormaznitsaProlDataTerm_TYPE_STRUCT) {
    result = (ComIgormaznitsaProlDataTermStruct *) check_class_cast(error_, [ComIgormaznitsaProlDataTermStruct class]);
  }
  else {
    result = [[ComIgormaznitsaProlDataTermStruct alloc] initWithComIgormaznitsaProlDataTerm:error_];
  }
  [((ComIgormaznitsaProlDataTermStruct *) nil_chk(result)) setCarriedObjectWithJavaIoSerializable:self];
  return result;
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlCustomErrorException *)other {
  [super copyAllFieldsTo:other];
  other->error_ = error_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithComIgormaznitsaProlDataTerm:withComIgormaznitsaProlDataTerm:", "ProlCustomErrorException", NULL, 0x1, NULL },
    { "getError", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
    { "getFunctorForErrorStruct", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
    { "getAsStruct", NULL, "Lcom.igormaznitsa.prol.data.TermStruct;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J" },
    { "error_", NULL, 0x12, "Lcom.igormaznitsa.prol.data.Term;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlExceptionsProlCustomErrorException = { "ProlCustomErrorException", "com.igormaznitsa.prol.exceptions", NULL, 0x1, 4, methods, 2, fields, 0, NULL};
  return &_ComIgormaznitsaProlExceptionsProlCustomErrorException;
}

@end
