//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlWrongGoalException.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlWrongGoalException_H_
#define _ComIgormaznitsaProlExceptionsProlWrongGoalException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/exceptions/ProlException.h"

#define ComIgormaznitsaProlExceptionsProlWrongGoalException_serialVersionUID 9055754857879445135LL

@interface ComIgormaznitsaProlExceptionsProlWrongGoalException : ComIgormaznitsaProlExceptionsProlException {
}

+ (long long int)serialVersionUID;
- (id)init;
- (id)initWithNSString:(NSString *)message;
- (id)initWithNSString:(NSString *)message
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)cause;
@end

#endif // _ComIgormaznitsaProlExceptionsProlWrongGoalException_H_
