//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlPermissionErrorException.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlPermissionErrorException_H_
#define _ComIgormaznitsaProlExceptionsProlPermissionErrorException_H_

@class ComIgormaznitsaProlDataTerm;
@class ComIgormaznitsaProlDataTermStruct;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"

#define ComIgormaznitsaProlExceptionsProlPermissionErrorException_serialVersionUID 7752699517532895102LL

@interface ComIgormaznitsaProlExceptionsProlPermissionErrorException : ComIgormaznitsaProlExceptionsProlAbstractCatcheableException {
 @public
  NSString *operation_;
  NSString *permissionType_;
}

+ (long long int)serialVersionUID;
+ (ComIgormaznitsaProlDataTerm *)TERM_ERROR;
- (id)initWithNSString:(NSString *)operation
          withNSString:(NSString *)permissionType
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)operation
          withNSString:(NSString *)permissionType
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)operation
          withNSString:(NSString *)permissionType
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (id)initWithNSString:(NSString *)operation
          withNSString:(NSString *)permissionType
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit;
- (NSString *)getOperation;
- (NSString *)getPermissionType;
- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct;
- (ComIgormaznitsaProlDataTermStruct *)getAsStruct;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlPermissionErrorException *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlExceptionsProlPermissionErrorException, operation_, NSString *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlExceptionsProlPermissionErrorException, permissionType_, NSString *)

#endif // _ComIgormaznitsaProlExceptionsProlPermissionErrorException_H_
