//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlException.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlExceptionsProlException_H_
#define _ComIgormaznitsaProlExceptionsProlException_H_

@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

#define ComIgormaznitsaProlExceptionsProlException_serialVersionUID -6503064090950753871LL

@interface ComIgormaznitsaProlExceptionsProlException : JavaLangRuntimeException {
}

+ (long long int)serialVersionUID;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)message
 withJavaLangThrowable:(JavaLangThrowable *)cause;
- (id)initWithNSString:(NSString *)message;
- (id)init;
@end

#endif // _ComIgormaznitsaProlExceptionsProlException_H_
