//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/exceptions/ProlTypeErrorException.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/igormaznitsa/prol/data/Term.h"
#include "com/igormaznitsa/prol/data/TermStruct.h"
#include "com/igormaznitsa/prol/exceptions/ProlAbstractCatcheableException.h"
#include "com/igormaznitsa/prol/exceptions/ProlTypeErrorException.h"
#include "java/lang/Throwable.h"

@implementation ComIgormaznitsaProlExceptionsProlTypeErrorException

static ComIgormaznitsaProlDataTerm * ComIgormaznitsaProlExceptionsProlTypeErrorException_TERM_ERROR_;

+ (long long int)serialVersionUID {
  return ComIgormaznitsaProlExceptionsProlTypeErrorException_serialVersionUID;
}

+ (ComIgormaznitsaProlDataTerm *)TERM_ERROR {
  return ComIgormaznitsaProlExceptionsProlTypeErrorException_TERM_ERROR_;
}

- (id)initWithNSString:(NSString *)validType
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  if (self = [super initWithComIgormaznitsaProlDataTerm:culprit withJavaLangThrowable:cause]) {
    self->validType_ = validType;
  }
  return self;
}

- (id)initWithNSString:(NSString *)validType
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit
 withJavaLangThrowable:(JavaLangThrowable *)cause {
  if (self = [super initWithNSString:message withComIgormaznitsaProlDataTerm:culprit withJavaLangThrowable:cause]) {
    self->validType_ = validType;
  }
  return self;
}

- (id)initWithNSString:(NSString *)validType
          withNSString:(NSString *)message
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit {
  if (self = [super initWithNSString:message withComIgormaznitsaProlDataTerm:culprit]) {
    self->validType_ = validType;
  }
  return self;
}

- (id)initWithNSString:(NSString *)validType
withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)culprit {
  if (self = [super initWithComIgormaznitsaProlDataTerm:culprit]) {
    self->validType_ = validType;
  }
  return self;
}

- (NSString *)getValidType {
  return validType_;
}

- (ComIgormaznitsaProlDataTerm *)getFunctorForErrorStruct {
  return ComIgormaznitsaProlExceptionsProlTypeErrorException_TERM_ERROR_;
}

- (ComIgormaznitsaProlDataTermStruct *)getAsStruct {
  ComIgormaznitsaProlDataTermStruct *result = [[ComIgormaznitsaProlDataTermStruct alloc] initWithComIgormaznitsaProlDataTerm:ComIgormaznitsaProlExceptionsProlTypeErrorException_TERM_ERROR_ withComIgormaznitsaProlDataTermArray:[IOSObjectArray arrayWithObjects:(id[]){ validType_ == nil ? [ComIgormaznitsaProlExceptionsProlAbstractCatcheableException UNDEFINED] : [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:validType_], [self getCulprit] == nil ? [ComIgormaznitsaProlExceptionsProlAbstractCatcheableException UNDEFINED] : [self getCulprit] } count:2 type:[IOSClass classWithClass:[ComIgormaznitsaProlDataTerm class]]]];
  [result setCarriedObjectWithJavaIoSerializable:self];
  return result;
}

+ (void)initialize {
  if (self == [ComIgormaznitsaProlExceptionsProlTypeErrorException class]) {
    ComIgormaznitsaProlExceptionsProlTypeErrorException_TERM_ERROR_ = [[ComIgormaznitsaProlDataTerm alloc] initWithNSString:@"type_error"];
  }
}

- (void)copyAllFieldsTo:(ComIgormaznitsaProlExceptionsProlTypeErrorException *)other {
  [super copyAllFieldsTo:other];
  other->validType_ = validType_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withComIgormaznitsaProlDataTerm:withJavaLangThrowable:", "ProlTypeErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withNSString:withComIgormaznitsaProlDataTerm:withJavaLangThrowable:", "ProlTypeErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withNSString:withComIgormaznitsaProlDataTerm:", "ProlTypeErrorException", NULL, 0x1, NULL },
    { "initWithNSString:withComIgormaznitsaProlDataTerm:", "ProlTypeErrorException", NULL, 0x1, NULL },
    { "getValidType", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getFunctorForErrorStruct", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x1, NULL },
    { "getAsStruct", NULL, "Lcom.igormaznitsa.prol.data.TermStruct;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J" },
    { "TERM_ERROR_", NULL, 0x1a, "Lcom.igormaznitsa.prol.data.Term;" },
    { "validType_", NULL, 0x12, "Ljava.lang.String;" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlExceptionsProlTypeErrorException = { "ProlTypeErrorException", "com.igormaznitsa.prol.exceptions", NULL, 0x1, 7, methods, 3, fields, 0, NULL};
  return &_ComIgormaznitsaProlExceptionsProlTypeErrorException;
}

@end
