//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/annotations/Consult.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlAnnotationsConsult_H_
#define _ComIgormaznitsaProlAnnotationsConsult_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComIgormaznitsaProlAnnotationsConsult < JavaLangAnnotationAnnotation >

@property (readonly) NSString *URL;
@property (readonly) IOSObjectArray *URLs;
@property (readonly) NSString *Text;
@property (readonly) IOSObjectArray *Texts;

@end

@interface ComIgormaznitsaProlAnnotationsConsult : NSObject < ComIgormaznitsaProlAnnotationsConsult > {
 @private
  NSString *URL;
  IOSObjectArray *URLs;
  NSString *Text;
  IOSObjectArray *Texts;
}

- (id)initWithText:(NSString *)Text_ withTexts:(IOSObjectArray *)Texts_ withURL:(NSString *)URL_ withURLs:(IOSObjectArray *)URLs_;

+ (NSString *)URLDefault;
+ (IOSObjectArray *)URLsDefault;
+ (NSString *)TextDefault;
+ (IOSObjectArray *)TextsDefault;

@end

#endif // _ComIgormaznitsaProlAnnotationsConsult_H_
