//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/annotations/Determined.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlAnnotationsDetermined_H_
#define _ComIgormaznitsaProlAnnotationsDetermined_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComIgormaznitsaProlAnnotationsDetermined < JavaLangAnnotationAnnotation >
@end

@interface ComIgormaznitsaProlAnnotationsDetermined : NSObject < ComIgormaznitsaProlAnnotationsDetermined >
@end

#endif // _ComIgormaznitsaProlAnnotationsDetermined_H_
