//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/annotations/Evaluable.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlAnnotationsEvaluable_H_
#define _ComIgormaznitsaProlAnnotationsEvaluable_H_

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComIgormaznitsaProlAnnotationsEvaluable < JavaLangAnnotationAnnotation >
@end

@interface ComIgormaznitsaProlAnnotationsEvaluable : NSObject < ComIgormaznitsaProlAnnotationsEvaluable >
@end

#endif // _ComIgormaznitsaProlAnnotationsEvaluable_H_
