//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/annotations/Predicate.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlAnnotationsPredicate_H_
#define _ComIgormaznitsaProlAnnotationsPredicate_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComIgormaznitsaProlAnnotationsPredicate < JavaLangAnnotationAnnotation >

@property (readonly) NSString *Signature;
@property (readonly) IOSObjectArray *Template;
@property (readonly) NSString *Reference;

@end

@interface ComIgormaznitsaProlAnnotationsPredicate : NSObject < ComIgormaznitsaProlAnnotationsPredicate > {
 @private
  NSString *Signature;
  IOSObjectArray *Template;
  NSString *Reference;
}

- (id)initWithReference:(NSString *)Reference_ withSignature:(NSString *)Signature_ withTemplate:(IOSObjectArray *)Template_;

+ (IOSObjectArray *)TemplateDefault;
+ (NSString *)ReferenceDefault;

@end

#endif // _ComIgormaznitsaProlAnnotationsPredicate_H_
