//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/annotations/Predicate.java
//
//  Created by katsura on 14/04/13.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/igormaznitsa/prol/annotations/Predicate.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"

@implementation ComIgormaznitsaProlAnnotationsPredicate
@synthesize Signature;
@synthesize Template;
@synthesize Reference;

- (id)initWithReference:(NSString *)Reference_ withSignature:(NSString *)Signature_ withTemplate:(IOSObjectArray *)Template_ {
  if ((self = [super init])) {
    Reference = RETAIN_(Reference_);
    Signature = RETAIN_(Signature_);
    Template = RETAIN_(Template_);
  }
  return self;
}

+ (IOSObjectArray *)TemplateDefault {
  return [IOSObjectArray arrayWithObjects:(id[]){  } count:0 type:[IOSClass classWithClass:[NSString class]]];
}

+ (NSString *)ReferenceDefault {
  return @"";
}


- (IOSClass *)annotationType {
  return [IOSClass classWithProtocol:@protocol(ComIgormaznitsaProlAnnotationsPredicate)];
}

+ (IOSObjectArray *)__annotations {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaLangAnnotationTarget alloc] initWithValue:[IOSObjectArray arrayWithObjects:(id[]) { [JavaLangAnnotationElementTypeEnum METHOD] } count:1 type:[[NSObject class] getClass]]], [[JavaLangAnnotationRetention alloc] initWithValue:[JavaLangAnnotationRetentionPolicyEnum RUNTIME]] } count:2 type:[IOSClass classWithProtocol:@protocol(JavaLangAnnotationAnnotation)]];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _ComIgormaznitsaProlAnnotationsPredicate = { "Predicate", "com.igormaznitsa.prol.annotations", NULL, 0x2201, 0, NULL, 0, NULL, 0, NULL};
  return &_ComIgormaznitsaProlAnnotationsPredicate;
}

@end

