//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/annotations/PredicateSynonyms.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlAnnotationsPredicateSynonyms_H_
#define _ComIgormaznitsaProlAnnotationsPredicateSynonyms_H_

@class IOSObjectArray;

#import "JreEmulation.h"
#include "java/lang/annotation/Annotation.h"

@protocol ComIgormaznitsaProlAnnotationsPredicateSynonyms < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *Signatures;

@end

@interface ComIgormaznitsaProlAnnotationsPredicateSynonyms : NSObject < ComIgormaznitsaProlAnnotationsPredicateSynonyms > {
 @private
  IOSObjectArray *Signatures;
}

- (id)initWithSignatures:(IOSObjectArray *)Signatures_;

@end

#endif // _ComIgormaznitsaProlAnnotationsPredicateSynonyms_H_
