//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/annotations/ProlOperators.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlAnnotationsProlOperators_H_
#define _ComIgormaznitsaProlAnnotationsProlOperators_H_

@class IOSObjectArray;

#import "JreEmulation.h"

@interface ComIgormaznitsaProlAnnotationsProlOperators : NSObject {
}

+ (IOSObjectArray *)Operators;
+ (void)setOperators:(IOSObjectArray *)Operators;
- (id)init;
@end

#endif // _ComIgormaznitsaProlAnnotationsProlOperators_H_
