//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/data/ConvertableToTerm.java
//
//  Created by katsura on 14/04/13.
//

#include "com/igormaznitsa/prol/data/ConvertableToTerm.h"
#include "com/igormaznitsa/prol/data/Term.h"


@interface ComIgormaznitsaProlDataConvertableToTerm : NSObject
@end

@implementation ComIgormaznitsaProlDataConvertableToTerm

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "asProlTerm", NULL, "Lcom.igormaznitsa.prol.data.Term;", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlDataConvertableToTerm = { "ConvertableToTerm", "com.igormaznitsa.prol.data", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComIgormaznitsaProlDataConvertableToTerm;
}

@end
