//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/data/NumericTerm.java
//
//  Created by katsura on 14/04/13.
//

#include "com/igormaznitsa/prol/data/NumericTerm.h"


@implementation ComIgormaznitsaProlDataNumericTerm

+ (int)NUMBER_INTEGER {
  return ComIgormaznitsaProlDataNumericTerm_NUMBER_INTEGER;
}

+ (int)NUMBER_FLOAT {
  return ComIgormaznitsaProlDataNumericTerm_NUMBER_FLOAT;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getNumericValue", NULL, "Ljava.lang.Number;", 0x401, NULL },
    { "compareWithComIgormaznitsaProlDataNumericTerm:", "compare", "I", 0x401, NULL },
    { "addWithComIgormaznitsaProlDataNumericTerm:", "add", "Lcom.igormaznitsa.prol.data.NumericTerm;", 0x401, NULL },
    { "subWithComIgormaznitsaProlDataNumericTerm:", "sub", "Lcom.igormaznitsa.prol.data.NumericTerm;", 0x401, NULL },
    { "divWithComIgormaznitsaProlDataNumericTerm:", "div", "Lcom.igormaznitsa.prol.data.NumericTerm;", 0x401, NULL },
    { "mulWithComIgormaznitsaProlDataNumericTerm:", "mul", "Lcom.igormaznitsa.prol.data.NumericTerm;", 0x401, NULL },
    { "neg", NULL, "Lcom.igormaznitsa.prol.data.NumericTerm;", 0x401, NULL },
    { "abs", NULL, "Lcom.igormaznitsa.prol.data.NumericTerm;", 0x401, NULL },
    { "sign", NULL, "Lcom.igormaznitsa.prol.data.NumericTerm;", 0x401, NULL },
    { "getNumberType", NULL, "I", 0x401, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "NUMBER_INTEGER_", NULL, 0x19, "I" },
    { "NUMBER_FLOAT_", NULL, 0x19, "I" },
  };
  static J2ObjcClassInfo _ComIgormaznitsaProlDataNumericTerm = { "NumericTerm", "com.igormaznitsa.prol.data", NULL, 0x201, 10, methods, 2, fields, 0, NULL};
  return &_ComIgormaznitsaProlDataNumericTerm;
}

@end
