//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/data/Operator.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlDataOperator_H_
#define _ComIgormaznitsaProlDataOperator_H_

@class ComIgormaznitsaProlDataTermStruct;
@class IOSObjectArray;
@class JavaIoPrintWriter;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/data/Term.h"

#define ComIgormaznitsaProlDataOperator_OPTYPE_FX 2
#define ComIgormaznitsaProlDataOperator_OPTYPE_FY 3
#define ComIgormaznitsaProlDataOperator_OPTYPE_XF 0
#define ComIgormaznitsaProlDataOperator_OPTYPE_XFX 4
#define ComIgormaznitsaProlDataOperator_OPTYPE_XFY 5
#define ComIgormaznitsaProlDataOperator_OPTYPE_YF 1
#define ComIgormaznitsaProlDataOperator_OPTYPE_YFX 6
#define ComIgormaznitsaProlDataOperator_PRIORITY_MAX 0
#define ComIgormaznitsaProlDataOperator_PRIORITY_MIN 1200

@interface ComIgormaznitsaProlDataOperator : ComIgormaznitsaProlDataTerm {
 @public
  int opType_;
  int opPriority_;
  int precalculatedHashCode_;
  NSString *signature_;
}

+ (int)PRIORITY_MAX;
+ (int)PRIORITY_MIN;
+ (int)OPTYPE_XF;
+ (int)OPTYPE_YF;
+ (int)OPTYPE_FX;
+ (int)OPTYPE_FY;
+ (int)OPTYPE_XFX;
+ (int)OPTYPE_XFY;
+ (int)OPTYPE_YFX;
+ (IOSObjectArray *)makeOperatorsWithInt:(int)priority
                                 withInt:(int)type
                       withNSStringArray:(IOSObjectArray *)names;
- (id)initWithInt:(int)priority
          withInt:(int)type
     withNSString:(NSString *)name;
- (int)getTermType;
- (int)getOperatorType;
- (int)getPriority;
- (BOOL)validateStructureForOperatorWithComIgormaznitsaProlDataTermStruct:(ComIgormaznitsaProlDataTermStruct *)struct_;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)obj;
- (NSString *)getSourceLikeRepresentation;
- (NSString *)description;
- (NSString *)getTypeAsString;
- (void)writeWithJavaIoPrintWriter:(JavaIoPrintWriter *)writer;
- (NSString *)getSignature;
- (NSString *)forWrite;
- (BOOL)EquWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
+ (NSString *)getTypeFromIndexWithInt:(int)index;
+ (int)getTypeFromStringWithNSString:(NSString *)op_type;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlDataOperator *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlDataOperator, signature_, NSString *)

#endif // _ComIgormaznitsaProlDataOperator_H_
