//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/data/TermList.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlDataTermList_H_
#define _ComIgormaznitsaProlDataTermList_H_

@class ComIgormaznitsaProlDataTerm;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/data/TermStruct.h"

#define ComIgormaznitsaProlDataTermList_INDEX_HEAD 0
#define ComIgormaznitsaProlDataTermList_INDEX_TAIL 1

@interface ComIgormaznitsaProlDataTermList : ComIgormaznitsaProlDataTermStruct {
}

+ (NSString *)LIST_FUNCTOR;
+ (ComIgormaznitsaProlDataTerm *)LIST_FUNCTOR_AS_TERM;
+ (ComIgormaznitsaProlDataTermList *)NULLLIST;
+ (int)INDEX_HEAD;
+ (int)INDEX_TAIL;
- (id)init;
- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term;
- (id)initWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)head
          withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)tail;
- (ComIgormaznitsaProlDataTerm *)getHead;
- (ComIgormaznitsaProlDataTerm *)getTail;
- (int)calculateLength;
- (void)setTailWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)newTail;
- (void)fillVarablesWithJavaUtilMap:(id<JavaUtilMap>)table;
- (BOOL)isNullList;
+ (ComIgormaznitsaProlDataTermList *)appendItemWithComIgormaznitsaProlDataTermList:(ComIgormaznitsaProlDataTermList *)list
                                                   withComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term;
- (BOOL)checkVariables;
- (int)getTermType;
- (NSString *)description;
- (NSString *)getSourceLikeRepresentation;
+ (NSString *)elementToSourceStringWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term;
- (void)replaceLastElementWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)newLastElement;
- (NSString *)getSignature;
- (NSString *)forWrite;
- (BOOL)EquWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (BOOL)equWithoutSetWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (int)termComparsionWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (BOOL)hasAnyDifferenceWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (BOOL)hasVariableWithNameWithNSString:(NSString *)name;
@end

#endif // _ComIgormaznitsaProlDataTermList_H_
