//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/data/Term.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlDataTerm_H_
#define _ComIgormaznitsaProlDataTerm_H_

@class ComIgormaznitsaProlDataTermList;
@protocol JavaIoSerializable;
@protocol JavaUtilMap;

#import "JreEmulation.h"

#define ComIgormaznitsaProlDataTerm_TYPE_ATOM 0
#define ComIgormaznitsaProlDataTerm_TYPE_LIST 5
#define ComIgormaznitsaProlDataTerm_TYPE_OPERATOR 3
#define ComIgormaznitsaProlDataTerm_TYPE_OPERATORS 4
#define ComIgormaznitsaProlDataTerm_TYPE_STRUCT 1
#define ComIgormaznitsaProlDataTerm_TYPE_VAR 2

@interface ComIgormaznitsaProlDataTerm : NSObject {
 @public
  NSString *termText_;
  id<JavaIoSerializable> carriedObject_;
}

+ (int)TYPE_ATOM;
+ (int)TYPE_STRUCT;
+ (int)TYPE_VAR;
+ (int)TYPE_OPERATOR;
+ (int)TYPE_OPERATORS;
+ (int)TYPE_LIST;
+ (ComIgormaznitsaProlDataTerm *)TERM_TRUE;
- (id<JavaIoSerializable>)getCarriedObject;
- (void)setCarriedObjectWithJavaIoSerializable:(id<JavaIoSerializable>)object;
- (id)initWithNSString:(NSString *)termText;
- (int)getPriority;
- (NSString *)getText;
- (int)getTermType;
- (BOOL)equWithoutSetWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)term;
- (BOOL)checkVariables;
- (void)fillVarablesWithJavaUtilMap:(id<JavaUtilMap>)table;
- (NSString *)getSourceLikeRepresentation;
- (NSString *)description;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)obj;
- (NSString *)getSignature;
- (NSString *)forWrite;
- (BOOL)EquWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)otherTerm;
- (ComIgormaznitsaProlDataTermList *)asCharList;
- (ComIgormaznitsaProlDataTermList *)asCharCodeList;
- (int)termComparsionWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (BOOL)hasAnyDifferenceWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)comparedTerm;
- (int)getTextLength;
- (BOOL)hasVariableWithNameWithNSString:(NSString *)name;
- (ComIgormaznitsaProlDataTerm *)makeClone;
- (ComIgormaznitsaProlDataTerm *)makeCloneWithJavaUtilMap:(id<JavaUtilMap>)variableSet;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlDataTerm *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlDataTerm, termText_, NSString *)
J2OBJC_FIELD_SETTER(ComIgormaznitsaProlDataTerm, carriedObject_, id<JavaIoSerializable>)

#endif // _ComIgormaznitsaProlDataTerm_H_
