//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/igormaznitsa/prol/data/Var.java
//
//  Created by katsura on 14/04/13.
//

#ifndef _ComIgormaznitsaProlDataVar_H_
#define _ComIgormaznitsaProlDataVar_H_

@class JavaUtilConcurrentAtomicAtomicInteger;
@protocol JavaUtilMap;

#import "JreEmulation.h"
#include "com/igormaznitsa/prol/data/Term.h"

@interface ComIgormaznitsaProlDataVar : ComIgormaznitsaProlDataTerm {
 @public
  ComIgormaznitsaProlDataTerm *value_;
  BOOL anonymous_;
  int variableUID_;
}

+ (JavaUtilConcurrentAtomicAtomicInteger *)NonamedVariableCounter;
+ (JavaUtilConcurrentAtomicAtomicInteger *)VariableUIDCounter;
- (id)initWithNSString:(NSString *)name;
- (id)init;
- (int)getVarUID;
- (int)getTermType;
- (ComIgormaznitsaProlDataTerm *)getValue;
- (BOOL)setValueWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)value;
- (void)fillVarablesWithJavaUtilMap:(id<JavaUtilMap>)table;
- (BOOL)isAnonymous;
- (NSString *)getSourceLikeRepresentation;
- (BOOL)isUndefined;
- (BOOL)checkVariables;
- (NSString *)description;
- (ComIgormaznitsaProlDataTerm *)getThisValue;
- (ComIgormaznitsaProlDataVar *)getDeepestVar;
- (void)setThisValueWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)value;
- (void)changeValueWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)value;
- (NSUInteger)hash;
- (BOOL)isEqual:(id)obj;
- (NSString *)getSignature;
- (NSString *)forWrite;
- (BOOL)EquWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (BOOL)equWithoutSetWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (int)termComparsionWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (BOOL)hasAnyDifferenceWithComIgormaznitsaProlDataTerm:(ComIgormaznitsaProlDataTerm *)atom;
- (BOOL)hasVariableWithNameWithNSString:(NSString *)name;
- (void)copyAllFieldsTo:(ComIgormaznitsaProlDataVar *)other;
@end

J2OBJC_FIELD_SETTER(ComIgormaznitsaProlDataVar, value_, ComIgormaznitsaProlDataTerm *)

#endif // _ComIgormaznitsaProlDataVar_H_
